### ISSUE TITLE
Spatial UX: SR3: Turn off aura

### ISSUE THREAD

**Issue by jafarigit** [WEKIT-ECS/MIRAGE-XR#1000]
I have noticed that when you are trying to add some augmentations on a table, the aura circle will come over the table and it will make both confusing and development issues for some of augmentations (eq. eRobson). It would be better if we could disable it on mobile since we have home button and the lists on screen now. We do not need the circle on mobile.

![Screenshot_20220717-112249_MirageXR](https://user-images.githubusercontent.com/15139692/179392295-d423847b-c807-4d35-84df-2cf4f0509d0e.jpg)

**Comment by fwild** [comment]
We discussed this in the past, and had found consensus in removing the aura, when to close to the user. So the aura would still be there, if you stand, but would be removed if you are closer than 1m (or so) to the aura. Can we agree on this?

**Comment by fominykh** [comment]
Can we allow a manual fix of the floor level?

**Comment by fwild** [comment]
@jafarigit do you want to implement it? We just discussed that manual fixing on the floor is not the solution, but we'd prefer to stay with the original suggestion: suppress display if closer to device than 1m, display if further away than 1m.

**Comment by jafarigit** [comment]
@fwild Sorry I didn't see your comment earlier. I can take this ticket while I'm working on eRobson augmentation. So by 1m you mean height, right? the distance between the floor and the device?

**Comment by fominykh** [comment]
I think this is the distance between the device of the user and the aura.

**Comment by fwild** [comment]
This is superseded now by fixing the aura to the floor level. But it still would be a nice extension to hide the aura when getting too close.

**Comment by fwild** [comment]
Superseded by this ticket: https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1882, closing.
