### ISSUE TITLE
SDK update - Advertising ID - Google Play

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1007]
Here is a message from Google:

Your app com.WEKIT.MirageXR version code 2166 includes SDK com.unity3d.ads:unity-ads or an SDK that one of your libraries depends on, which collects personal or sensitive data that includes but may not be limited to Advertising ID, Android ID identifiers. Persistent device identifiers may not be linked to other personal and sensitive user data or resettable device identifiers as described in the [User Data](https://support.google.com/googleplay/android-developer/answer/10144311) policy.

Starting from October 1, 2022 midnight (UTC), new app releases containing the SDK version(s) that do not comply with the [User Data](https://support.google.com/googleplay/android-developer/answer/10144311) policy may be blocked from release. You may consider upgrading to a policy-compliant version of this SDK that does not include the violating code if available from your SDK provider, or removing this SDK from your app.

According to the information provided by your SDK provider, you may consider upgrading to 4.0.1. Please consult the SDK provider for further information.

ACTION REQUIRED: Upload a new compliant version AND deactivate the noncompliant version.

Read through the [User Data](https://support.google.com/googleplay/android-developer/answer/10144311) policy for more details, and how to submit an updated app for review [here](https://support.google.com/googleplay/android-developer/answer/2477981#resubmit).

If you've reviewed the policy and feel our decision may have been in error, please reach out to our [policy support team](https://support.google.com/googleplay/android-developer/contact/appwarning?ts=sdk&src=com.unity3d.ads:unity-ads).

**Comment by BenediktHensen** [comment]
Is this still relevant?

I think we can remove the com.unity3d.ads:unity-ads package entirely. It is probably only included in the project since it was there from the start in the default Unity project. It is not actively used as its purpose is to show advertisements in the app which we do not need.

**Comment by fwild** [comment]
Agree!

**Comment by fwild** [comment]
Yes, still relevant. Last email in app console was flagged on Dec 21:

Your app includes non compliant SDK version
MirageXR MirageXR
Dec 21, 2022 17:02

Your app com.WEKIT.MirageXR version code 2168 includes SDK com.unity3d.ads:unity-ads or an SDK that one of your libraries depends on, which collects personal or sensitive data that includes but may not be limited to Advertising ID, Android ID identifiers. Persistent device identifiers may not be linked to other personal and sensitive user data or resettable device identifiers as described in the [User Data](https://support.google.com/googleplay/android-developer/answer/10144311) policy.

Starting from January 11, 2023 midnight (UTC), new app releases containing the SDK version(s) that do not comply with the [User Data](https://support.google.com/googleplay/android-developer/answer/10144311) policy may be blocked from release. You may consider upgrading to a policy-compliant version of this SDK that does not include the violating code if available from your SDK provider, or removing this SDK from your app.

According to your SDK provider, you may consider upgrading to 4.0.1, and/or contacting your SDK provider to see if a suitable later version might be available. Google is unable to endorse or recommend any third party software.

ACTION REQUIRED: Upload a new compliant version AND deactivate the noncompliant version.

Read through the [User Data](https://support.google.com/googleplay/android-developer/answer/10144311) policy for more details, and how to submit an updated app for review [here](https://support.google.com/googleplay/android-developer/answer/2477981#resubmit).

If you've reviewed the policy and feel our decision may have been in error, please reach out to our [policy support team](https://support.google.com/googleplay/android-developer/contact/appwarning?ts=sdk&src=com.unity3d.ads:unity-ads).
[Learn More](https://support.google.com/googleplay/android-developer/answer/10358880)

**Comment by robhillman97** [comment]
I have just removed the advertising SDK via package manager and pushed the changes to a feature branch:

https://github.com/WEKIT-ECS/MIRAGE-XR/commit/df222707414af05f69f052bc4bc8a119fadab3db

is this all that is required? if so I'll make a PR
