### ISSUE TITLE
Refactor ImageTargetController into ImageTargetManager

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#1013]
Currently, we have already an implementation, but it does not have a register routine, and some of the code seems specific to the launch of activity editor:

https://github.com/WEKIT-ECS/MIRAGE-XR/blob/eROBSON_Project/Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation%20Editors/ImageMarker%20Prefabs/ImageMarkerController.cs

Code of eRobson currently registers a full image library with all targets at once, and handles the onImageChanged event handler from AR foundation in the eRobson specific way:

https://github.com/WEKIT-ECS/MIRAGE-XR/blob/eROBSON_Project/Assets/MirageXR/Player/Prefabs/eROBSON/Scripts/ERobsonImageMarkerController.cs 

We should integrate a registration method into the generic MirageXR ImageMarkerController class, 

registerImageTarget(string filename, callback)

and an imageLibrary
private XRReferenceImageLibrary serializedLibrary;

trackImageManager.maxNumberOfMovingImages needs to go up to probably 5?

We should rename the class to ImageTargetManager and relocate it to a different folder.

**Comment by fwild** [comment]
Whether the register routine accepts only strings with filename or an image instead (an item of the XRReferenceImageLibrary) - that can be still discussed!

**Comment by cawke** [comment]
How I see it
https://drive.google.com/file/d/1BhAzOOPH9RsN_f1rQBYfvL0MTX1Xfc5h/view?usp=sharing
![image](https://user-images.githubusercontent.com/20320355/183905199-59bf1254-9c8e-4694-8f45-bfb06187b667.png)
