### ISSUE TITLE
UI_Kit

### ISSUE THREAD

**Issue by cawke** [WEKIT-ECS/MIRAGE-XR#1021]
Сreate a set of basic prefabs

Texts
![image](https://user-images.githubusercontent.com/20320355/186023155-f5c6e42c-12c8-46a2-b351-eb6970e025c4.png)

Buttons
![image](https://user-images.githubusercontent.com/20320355/186023231-5fb3f709-a189-4070-8db1-6bed39f40dda.png)

Text Field
![image](https://user-images.githubusercontent.com/20320355/186023271-03cac941-52f5-4c01-b93a-d75e36bd64f6.png)

Toggels/checkbox
![image](https://user-images.githubusercontent.com/20320355/186023333-ed0bc39f-35ba-4734-a599-66d8d9f0eadd.png)

Dropdown
![image](https://user-images.githubusercontent.com/20320355/186023358-0ff5d6b0-1ab8-4593-98d0-1142b4fcd6e1.png)

Others
![image](https://user-images.githubusercontent.com/20320355/186023427-9126f7c6-323c-448a-80e8-b16648e96ff1.png)

**Comment by Alvareon** [comment]
https://github.com/WEKIT-ECS/MIRAGE-XR/pull/1027
