### ISSUE TITLE
add trigger to ghost: fix audio step trigger on ghost

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#1066]
When recording the audio of the ghost, it is already possible to set the audio trigger (to advance to the next step automatically, once audio finishes playing). It seems, because we bypass the normal audio play routines in the ghost controller, that the trigger is not actually executed. Fix.

**Comment by fwild** [comment]
@robhillman97 I think this is fixed in one of the hotfixes (to be merged?), right?

**Comment by robhillman97** [comment]
Not this one, I haven't looked into it yet

**Comment by robhillman97** [comment]
Just tested this and it seems to work now with the new audio trigger updates, provided you are in play mode.
