### ISSUE TITLE
Create a panel "keep alive 2-2"

### ISSUE THREAD

**Issue by Alvareon** [WEKIT-ECS/MIRAGE-XR#1096]
![Picker](https://user-images.githubusercontent.com/34060044/199630263-7ce86b30-d9c2-4331-badd-b86c5e3859a4.png)

**Comment by fwild** [comment]
@Alvareon - are you back on this now or should I still change to @cawke? Any chance we can have this done by Thursday, so we can finish work up on Version 2?
