### ISSUE TITLE
Preview image does not appear on the list of activities

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1106]
How to reproduce:
1. Create or open activity
2. Upload a preview thumbnail image
3. Save activity
4. Find the activity in the list of Activities and observe that the preview image did not change from the default one

![image](https://user-images.githubusercontent.com/10297277/202027976-6ae25b2d-7d0e-44c5-9b0d-2cc462b338ad.png)

**Comment by fwild** [comment]
I don't think we can release this feature with version 2.0 - we are still quite far away from it, and at the moment, deployment for Moodle is stuck because of lack of a testing site. Shall we move this to 2.1?
