### ISSUE TITLE
The add new step element disappears when tapping on it

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1107]
How to reproduce:
1. Open activity to edit
2. Open steps
3. Tap on the Add new step "stripe" element (not on the + symbol)
4. Observe that the element disappears
5. Switch edit off and on to get the element back

**Comment by fwild** [comment]
I can reproduce this, same prob here on my device (Android)

**Comment by fwild** [comment]
Maybe simply remove the drag & drop option for the "add new step" for now, then it should not happen?

**Comment by fwild** [comment]
@cawke in the latest pipeline build, this problem no longer appears - did you fix it? Let's close this ticket...

**Comment by fwild** [comment]
There is still one bug: it inserts at 'here+1', not at 'here', indicating a step counter problem.
So: if you have step 1/2/3, move it to before step 2, you get 1/2/4/3, not 1/4/2/3

**Comment by fwild** [comment]
Related to: https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1177

**Comment by fwild** [comment]
Closing, as this has been replaced by newer ticket.
