### ISSUE TITLE
Context help: add calibration

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#1140]
when editing an activity:
* why and how to calibrate?: Calibration ensures that all locations in 3D space are correct next time you or someone else opens the activity. Each activity needs to be calibrated when editing and when viewing. To calibrate, tap the 'calibration' tab and start calibration.

**Comment by BorisJov** [comment]
We already have this in the calibration tab. Should we also add it elsewhere?

**Comment by fwild** [comment]
Ah, yes, I think we need to mention this in the context help earlier - should be in the first list, when entering editmode and playmode!

**Comment by BorisJov** [comment]
Since there are already quite a few help items in the first activity screen, I'll change the current 'How to calibrate' to 'How and why to calibrate' and add the above text

**Comment by BorisJov** [comment]
Done in hotfix to develop

**Comment by fwild** [comment]
I have tested it, closing this ticket.
