### ISSUE TITLE
Show step name / number in minimized menu view (prev/next)

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#1156]
<img width="235" alt="Screenshot 2022-12-15 at 15 54 49" src="https://user-images.githubusercontent.com/183296/207907098-f6131370-0db9-4dca-b651-3bdef918a855.png">

**Comment by Alvareon** [comment]
@fwild You mean replace prev/next with a name/number? Or just adding text to prev/next?

**Comment by Alvareon** [comment]
https://github.com/WEKIT-ECS/MIRAGE-XR/pull/1290
