### ISSUE TITLE
Bunch of small items

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#1158]
- the intro slides should come before the login
- SSO button does not work, hide for now?
- remove 'old design' / 'new design' switching option
- minimizing "home" (the activity list): move the "by date" and the "show all" slightly lower, so that these are not visible on the minimized home card anymore ![WhatsApp Image 2022-12-15 at 15 25 15](https://user-images.githubusercontent.com/183296/207899942-9ca20b96-c432-44d9-9626-288d70fe0fa2.jpeg)
- if an activity has a deadlines set (search for "caretta"): they show up as 1.1.1970, so either they come through wrong from Moodle, or they are not correctly parsed?
- opening an activity for "viewing": can we open with the calibration tab opened? And add text after "to calibrate the activity.": "to calibrate the activity. Once calibrated, this window will disappear, and the activity will start."
- after successful calibration, open the steps list and minimize to show the "prev/next step" view
- sketchfab login: the button labels are too big 
![WhatsApp Image 2022-12-15 at 16 12 42](https://user-images.githubusercontent.com/183296/207911255-43f0dabf-d38a-4248-b289-a528d14e6f40.jpeg)
- sketchfab SSO: broken (the redirect url server wekit-community.org does not exist anymore), hide for now
- add manipulation bounding box handles to 3D model in edit mode (and make disappear in playmode)
- trigger for 3D models does not work
- when switching to play mode (via the switch: edit mode off): return to action step list, if the menu was on edit step (otherwise all the edit options will still be available)
- Home: restart activity / back to activity are bit too squeezed in - increase spacing to "Home screen" and activity list?
- step panel: Image marker tab: text should be displayed that the feature is available as augmentation (for now): add a new image marker augmentation

**Comment by robhillman97** [comment]
I wanted to talk about the onboarding slides in the meeting but forgot to mention it. I set them up to show after logging in as the last page asks about starting the tutorial so thought it would make more sense to go straight from this page into the tutorial rather then asking you to log in and then going into the tutorial. 

I can change if we disagree, what do you think?

**Comment by fwild** [comment]
Good point, then again the slide before tells you that you can login, or just login as guest. Let's leave it as is then, but somehow its not fully logical.
