### ISSUE TITLE
Step panel's marker tab to replace image marker augmentation

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#1160]
When clicking edit step, there is a "marker" tab, which should be the new interface for adding image markers. This should replace the existing image marker augmetnation, and integrate this feature on the action step level instead.

**Comment by fwild** [comment]
We might still want to create a new image marker augmentation later at some point, but then more as a "display 3D model over piece of paper" sort of feature?

**Comment by Alvareon** [comment]
I moved ImageMarker from "Select augmentatuon type" to tab "Marker": https://github.com/WEKIT-ECS/MIRAGE-XR/pull/1300
