### ISSUE TITLE
Add-Augmentation-Dialogue Arrow Not Working

### ISSUE THREAD

**Issue by BorisJov** [WEKIT-ECS/MIRAGE-XR#1161]
The arrow at the top of the augmentation type selection isn't doing anything:
![image](https://user-images.githubusercontent.com/30473641/207949444-74054076-0f40-45a9-aa0b-9d1c06dcf3dc.png)

**Comment by fwild** [comment]
The reason for this is probably that the "add augmentation from list" dialogue is open, and it is blocking interaction with the background.

Thought about what you said, and I tend to agree here that this should probably just be greyed out or removed on this particular dialogue, as one should close the blocking "add augmentation" dialogue first.
