### ISSUE TITLE
Hololens builds not working 

### ISSUE THREAD

**Issue by robhillman97** [WEKIT-ECS/MIRAGE-XR#1170]
HoloLens builds are opening in windowed mode; 

![20221220_090309_HoloLens](https://user-images.githubusercontent.com/65968011/208628864-f4e8f9fd-47d2-48bd-8665-98ecb7f25c05.jpg)
![20221220_090330_HoloLens](https://user-images.githubusercontent.com/65968011/208628886-3610d913-dae6-4cbd-a56f-def2e89944a8.jpg)

Looks like this is related to updating to unity 2021.3.8f1 as they have removed the Legacy Built-in XR and it has been fully replaced with the OpenXR plugin which has not been configured for our project: 

https://learn.microsoft.com/en-us/windows/mixed-reality/develop/unity/choosing-unity-version

**Comment by fwild** [comment]
Dang, yes, but let's get version 2 mobile out first, before we turn to that!
