### ISSUE TITLE
Rename “activity settings” to “Publish”

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#1184]
Let's rename the text to "Publish...". 

Let's make "cloud" the default option.

**Comment by fwild** [comment]
@fedfomi @fominykh what do you think?

**Comment by fominykh** [comment]
The thinking was that we will later have more settings/actions in the Activity settings.

**Comment by fwild** [comment]
Maybe we should also add a “save” icon and “cloud upload” icon on top of the UI - beside the edit toggle?
