### ISSUE TITLE
Onboarding animation on slide 5 is more blurry than others and a black line appears on top

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1187]
Currently, 

The onboarding animation on slide 5 is more blurry than others and a black line appears on top.

Should be:

1. Can we try to make the animation sharper? The original is much sharper...
2. There is a little black line over the head of the person on the animation. It is a bug. The line can be cut from the animation.

**Comment by fwild** [comment]
@cawke can you help convert? the problem seems to come from using an online converter for the gifs, as they needed to be converted to sprite sheets.
