### ISSUE TITLE
Recalibration button stays visible after the screen is minimized.

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1188]
![Screenshot_20221222-201716_MirageXR.jpg](https://user-images.githubusercontent.com/10297277/209227995-72cf84dd-2f6b-4f93-baae-50cdae98ebad.jpg)

**Comment by fwild** [comment]
same as https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1174

**Comment by Alvareon** [comment]
@fominykh What device did you use? Looks like it's already fixed:

![recalibration](https://user-images.githubusercontent.com/34060044/218579847-cae3d699-064e-4ec3-911b-f6e1a107139c.gif)

**Comment by fominykh** [comment]
it was on Android, S9.
I remember that the Recalibration button disappeared correctly if I switched to Info or Steps tabs, but not when minimizing. I cannot reproduce the bug anymore.
