### ISSUE TITLE
Recalibration is unstable

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1189]
I am testing the Android version from 22.12.2022.
How to reproduce:
1. create a new activity
2. add an action to the first step, move it
3. add an image to the first step, move it
4. Recalibrate and observe that the augmentations are on the same places.
5. Edit activity name and description, walk around the room with the phone. Observe that the augmentations moved or disappeared.
6. Recalibrate and observe that the augmentations are back, but not where you placed them. The augmentations moved around 2 meters in the same direction.
7. Send phone to sleep.
8. Wake phone up and recalibrate. Observe that the augmentations are back to the correct location, where I placed them originally,
9.

**Comment by fwild** [comment]
I think this is because recalibration reloads the activity and then restarts at step 1. This causes another small bug, though.

**Comment by fwild** [comment]
If you save the activity to local before recalibration, does this still happen?

**Comment by fominykh** [comment]
When I saved the activity locally -> reopen the activity -> calibrate -> works fine.

**Comment by fwild** [comment]
To check: check if the activity is autosaved for any editing activity; if not, then we need to display a warning that you are about to reload the activity, potentially undoing any changes since last save (or so).

**Comment by fwild** [comment]
@fominykh can you please validate that this ticket is now resolved and close it?

**Comment by fominykh** [comment]
I tested earlier today and did not experience unstable calibration. The issue can be closed.
