### ISSUE TITLE
Re-shuffleing steps is not implemented, so the (i) item needs to be updated 

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1190]
Currently,

The (i) contextual help item says that the user can re-shuffle steps in an activity, but the user cannot do it.

Should be:

The (i) contextual help item should not say anything about it.

**Comment by BorisJov** [comment]
This is the multiple steps item, right? So should I just remove the second sentence in the explanation?

**Comment by fominykh** [comment]
correct

**Comment by BorisJov** [comment]
Done in hotfix push to develop.
