### ISSUE TITLE
Vuforia bug without wifi

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1193]
Starting the app (dev) on Android, without WiFi.
Get this error:
![Screenshot_20230104-120756_MirageXR.jpg](https://user-images.githubusercontent.com/10297277/210562248-f931cf9b-2c3c-4613-887d-146d447386ce.jpg)

**Comment by fwild** [comment]
Should be only happening if this is the first time you opened the app. If you had opened it before (while being online), the error should not appear.

**Comment by fwild** [comment]
Should interestingly not be there at all, as we have phased out Vuforia from mobile completely.
