### ISSUE TITLE
3d model augmentation: edit opens 'action' aug edit panel

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#1204]
When I add a 3D model, and then later click via context menu on 'edit', it brings up the wrong edit panel (that of 'action').
Dupe: https://github.com/WEKIT-ECS/MIRAGE-XR/issues/980

**Comment by robhillman97** [comment]
Do you still have this issue in version 2?

Just tried the android store version and the edit button opens the model editor as expected:

https://drive.google.com/file/d/12clA-g5ziHjSLZHQdNBJcQl8Ks9sIGML/view?usp=sharing

**Comment by fwild** [comment]
I still get the error, but only when I use the Mars Rover (3rd one in the list) as the 3D model - then it is added as "action". All other models I add are correctly listed as "model" (and then open the model editor panel).
