### ISSUE TITLE
calibration > get marker not working

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#1205]
Should open the marker in the browser, I assume:
https://wekit-ecs.com/public/uploads/images/MIRAGE-XR-Calibration-Marker.png

**Comment by Alvareon** [comment]
@fwild, added function to share the calibration image to email, messengers or printer directly from the application.
The user can quickly print the calibration image. For convenience, the image file is converted to pdf format of A4 size.

![demo_sharing_resize](https://user-images.githubusercontent.com/34060044/218202983-5837ab6f-3e00-4c06-ab32-62eb15f79822.gif)


https://github.com/WEKIT-ECS/MIRAGE-XR/pull/1259
