### ISSUE TITLE
Redesign activity list to show status visually

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#1220]
Find a unobtrusive way to display if an activity in the list is:
* Local only
* Already downloaded
* In a course (= pending assignment)
* completed
* Currently open
* Authored by current user

**Comment by fwild** [comment]
@fedfomi do we have a design for this already?

**Comment by fominykh** [comment]
We are in the process of re-working the activity list in the Spatial UI now. We can fill in the mobile UI after that.

**Comment by fominykh** [comment]
1. Need your feedback @fwild on the design draft
2. The list of items in the issue description is no longer up to date. e.g. we do not need "Local only" and "Already downloaded", right?
![image](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/10297277/bf26c9b6-7c6c-4c94-80d9-691232fc9a99)
