### ISSUE TITLE
Update UI v2 according to the design comments in Figma

### ISSUE THREAD

**Issue by Alvareon** [WEKIT-ECS/MIRAGE-XR#1224]
The design comments: 
https://www.figma.com/file/AqAGvX0KRDNRlVz3KFzoMH/New-Concept?node-id=2213%3A19785&t=EEG49AhdBpvPmhOl-0

**Comment by Alvareon** [comment]
https://github.com/WEKIT-ECS/MIRAGE-XR/pull/1225 - part1

**Comment by Alvareon** [comment]
https://github.com/WEKIT-ECS/MIRAGE-XR/pull/1231 - part 2

**Comment by Alvareon** [comment]
https://github.com/WEKIT-ECS/MIRAGE-XR/pull/1236 - part 3

**Comment by Alvareon** [comment]
https://github.com/WEKIT-ECS/MIRAGE-XR/pull/1239 - part 4

**Comment by fwild** [comment]
few items still missing, new issues created / coming
