### ISSUE TITLE
Auto-safe for keep alive

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1234]
How to reproduce:
1. In step 1, add an image augmentation.
2. Create step 2.
3. Open step 1, select the earlier created image augmentation, and select keep alive 1-2.
4. Open step 2, and observe that the same image augmentation also appears in step 2.
5. [updated] Autosaving does not work here. Close the app on this step without saving in the "Publish" menu.
6. Open activity. And observe that step 2 does not exist anymore.

The bug does not appear if I "save-to-local-device" on step 5.

Related to: https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1217

**Comment by fwild** [comment]
So: What needs to be done: make autosave when adding keep alive
