### ISSUE TITLE
Deleted 3D models not removed from activity JSON

### ISSUE THREAD

**Issue by robhillman97** [WEKIT-ECS/MIRAGE-XR#1238]
If you delete a 3D model augmentation, the model files are deleted but the augmentation is not correctly deleted from the activity JSON. This throws a null reference exception as the JSON tells Mirage to search for a file that does not exist any more

**Comment by fwild** [comment]
Just tested on latest Android: does not happen here:

![Screenshot 2023-01-26 at 14 36 18](https://user-images.githubusercontent.com/183296/214863828-bb9bf27a-d8d4-414b-9412-99c60c5068b9.png)

**Comment by robhillman97** [comment]
Cannot be reproduced so seems to have been fixed in version 2
