### ISSUE TITLE
Add Image/Video from library

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#1252]
Implement the dialogue (as already foreseen, but not functional, for Thumbnails).

**Comment by Alvareon** [comment]
https://github.com/WEKIT-ECS/MIRAGE-XR/pull/1298

**Comment by Alvareon** [comment]
![add_image_from_gallery](https://user-images.githubusercontent.com/34060044/227027358-cb3adf70-4fd9-4d79-9d70-9745f4efb95d.gif)
