### ISSUE TITLE
Add repository URL and LRS URL to BrandConfigurator

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#1274]
Allow to set the URLs for Moodle and the xAPI learning record store in the BrandConfigurator - and subsequently suppress the dropdown choice for both from the profile menu.

**Comment by jafarigit** [comment]
The Moodle URL and xAPI URL have been added to brandConfiguration, but they are not yet being used in the app. Developers who have refactored MoodleManager, DBManager, and other components can utilize these variables through the new static class ConfigParser by accessing ConfigParser.MoodleUrl and ConfigParser.XApiUrl.
BrandManager also has been refactored. The augmentations list will now be created using the ContentType enum, eliminating the need for two separate arrays. This change streamlines the process, getting rid of unnecessary splitting and replacing between augmentation names, predicates, and so on.

https://github.com/WEKIT-ECS/MIRAGE-XR/pull/1344

**Comment by fwild** [comment]
I think this still requires to use the ConfigParser.MoodleURL etc.

**Comment by fwild** [comment]
We already have a new ticket for the remainder work, therefore closing.
