### ISSUE TITLE
Calibration Start Button Excess Step

### ISSUE THREAD

**Issue by BorisJov** [WEKIT-ECS/MIRAGE-XR#1294]
Currently when in the calibration tab, if you want to calibrate, you have to first press start.
Then, an additional popup comes from below asking if you want to start calibrating or get the calibration image.
It seems a bit superfluous to have to click two times, especially since getting the calibration image won't be clicked as much.
Why not just add an additional button (slightly differently coloured and smaller) for getting the image  underneath Start
in the tab's main field? Would probably be more intutive and there's plenty of room.

<img width="266" alt="image" src="https://user-images.githubusercontent.com/30473641/223765520-bb35489d-1e46-4263-9e20-9bd173888188.png">
<img width="274" alt="image" src="https://user-images.githubusercontent.com/30473641/223765614-b61c487b-4e7d-4681-a2fb-077cdae55966.png">

**Comment by fwild** [comment]
Has now been superseded by the redesign with manual placement. closing.
