### ISSUE TITLE
The calibration marker orientation should not affect the rotation of augmentations when they spawn

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1295]
Currently,
1. Put the calibration marker vertically on a wall.
2. Start the app
3. Create new activity
4. Calibrate
5. Add Action glyph "Green Checkmark".
6. Observe that the glyph appears lying horizontally.
7. Move the calibration marker horizontally on the floor
8. Calibrate
9. Add Action glyph "Green Checkmark".
10. Observe that the glyph appears standing vertically.

Should be,
The green checkmark glyph should appear standing up vertically regardless of the position of the calibration marker.

This issue applies also to som other augmentation types.

**Comment by fwild** [comment]
Orientation for calibration should always be: centre of the calibration marker + Vector3.Up
