### ISSUE TITLE
Verbosity level slider UI for the Settings page after the debug mode is activated

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1317]

**Comment by fominykh** [comment]
@BenediktHensen can you write what are the names of the 5 levels?

**Comment by BenediktHensen** [comment]
The verbosity levels are:
1. Fatal: severe errors which may lead to crashes
2. Error: other detected errors
3. Warning: if the program detects an unforseen state which might lead to an error down the line
4. Info: general information about major actions that the app is performing
5. Debug: more details about what the app does, e.g., outputs of individual values to gain a higher understanding of the current state of the app
6. Trace: very detailed logs which help developers understand which code execution path the app is taking, e.g., method calls, logs in if-else branches

The levels are like priorities (1 is the highest priority and will always be put into the log, 6 is the lowest priority).

The system lets you set the minimum log level. For instance, if you set it to "Info", it means that logs of level Info, Warning, Error and Fatal are output but Debug and Trace are suppressed. If you set it to "Error", only "Error" and "Fatal" logs are output. If you set it to "Trace", log messages of all levels are output.

"Info" is the standard level on which the app starts.

**Comment by fominykh** [comment]
@BenediktHensen are these 3 icons correspond to the verbosity levels? Are there icons for all 6?

![image](https://user-images.githubusercontent.com/10297277/229311950-c6a18d6d-d6f9-4e77-a806-995475b09659.png)

**Comment by fominykh** [comment]
design source in Figma
![image](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/10297277/ea99660e-d2c6-4b1d-846e-e6e317d9ffdd)
