### ISSUE TITLE
Snap to grid

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#1327]

**Comment by fwild** [comment]
Snapping
* Using flat physical surfaces: floor and walls (and other augmentations) to snap augmentations to.

Manipulation of augmentations
* snap to grid when moving
* snap to defined angle when rotating
* snap to defined power when scaling

Grid
* automatically detect the floor vector, choose x-axis, and floor level (or ask the user to confirm the level)
* add the "Grid" property setting (globally), where the user can define (a) the floor level, (b) x axis, and (c) snap/grid step.

**Comment by fwild** [comment]
Open questions:
* grid size? rotation angles? scaling factor?
* lock origin of the grid? (floor plane? calibration marker? both?)

**Comment by fwild** [comment]
More info: https://github.com/WEKIT-ECS/MIRAGE-XR/issues/598

**Comment by fwild** [comment]
- allow to set the grid origin by function
- allow to set grid size globally in profile > group: preferences
- allow to set rotation angles globally in profile > group: preferences
- standard size: 5 cm
- standard grid angle: 0 degrees
- set y origin automatically to floor plane
- set x+z axes to marker x+z origin
- rotation of the grid is set by x+z axes of marker
- allow to lock augmentations via the augmentation list (lock icon)
- placement (drop): cast shadow onto spatial map (light source is orthogonal to the floor plane; shadows to fall also onto other augmentations; maybe also additionally to a wall plane?)
- movement with snap to grid: objects jumps between positions
- rotation handles to snap to 5 degrees 
- tap twice to bring up context menu: move, rotate, scale; tap third time to release
- rotation: put finger on, rotate
- before release: show current rotation angle from origin of rotation
- before release: show xyz distance from origin of movement

**Comment by jafarigit** [comment]
I have implemented snap effect for eRobson augmentations using raycast and it works fine now. Before I user colliders (Trigger and collision) but had many issues. So if it helps, you (the developer(s) who will work on this issue) can just check eRobson branch and use the codes I already have written.
Also we can ideally move that part of code to a new class in core and then all augmentation including eRobson and even environment use that class.

**Comment by fwild** [comment]
Add additional smaller steps for grid size: 0.5cm 1cm 2cm, but show only every 10th grid point

**Comment by fwild** [comment]
but maybe not needed if the snap to environment / snap to other object works

**Comment by fwild** [comment]
6.25 cm, 12.5cm, 25cm (as 1/8m is a standard step size measure in the built environment)

**Comment by fwild** [comment]
For grid snap: centre of the object, for snap to other objects: surface snapping

**Comment by fominykh** [comment]
@fwild can we close this issue?
