### ISSUE TITLE
Built Environment: set of 3D models + primitives

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#1330]
Standard size: https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1455
Placement: 

* make sure that objects that are to be put on the floor (e.g. wheelbarrow) really have the boundary box exactly around the floor plane
* orientation-lock: wouldn't it be neat, if we would allow to lock the orientation, so that users only move the object (with grid snap)?
* pivot points need to be sensibly set (otherwise, e.g., scaling the garage becomes impossible)
* allow to enter values directly

**Comment by fwild** [comment]
Standard set of 3D models (brick, bucket, tile, tools...)
Standard set of 3D shape primitives (configure dimensions for cylinder, wall, surface, ...)

**Comment by fwild** [comment]
If needed, we could investigate to do this as addressables or via sketchfab libraries.

**Comment by fominykh** [comment]
1 folding rule
2 construction pencil
3 rope
4 mortar bucket
5 masonry hammer
6 trowel
7 spirit level
8 set squares
9 feather-edge / steel straight-edge 
10 shovel
11 wheel-barrow

**Comment by fwild** [comment]
Related: https://github.com/WEKIT-ECS/MIRAGE-XR/issues/593

**Comment by fwild** [comment]
**whole collections**
* this here is a whole collection of low poly tools: https://sketchfab.com/3d-models/50-low-poly-tools-3453c7da36834a8d81efdb93fed6d466
* https://sketchfab.com/3d-models/low-poly-tools-pack-b7892e52af474dffaf00a974aa974940
* https://www.turbosquid.com/3d-models/3d-collection-of-smallsize-lowpoly-items-for-construction-model-1877168
* 

**1: folding ruler**

* We should definitely put a standard folding ruler 3D model in, so it can be used in instruction; but, unless we animate it and make it interactive, it cannot be directly used - and I am not sure the effort needed in animation pays off?
* I could imagine we should also add tape measures: https://sketchfab.com/3d-models/construction-measuring-tapes-ruler-867f2f15d871459689fe6e43033d0ac6 - animation here is a tad easier, and maybe this could be integrated into the redesign of the ruler?
* what about a caliper? https://sketchfab.com/3d-models/caliper-3ec3cc1378234b5e92817d2f4fa880e1

**2: construction pencil**
* https://sketchfab.com/3d-models/timmermanspotlood-bouwpotlood-ceb2a98b15f04e1eb25e52731c7f795a

**3: rope**
* https://sketchfab.com/3d-models/rope-461d2a0d745647a582a78972a70d25c3
* https://sketchfab.com/3d-models/rope-7dce7f24ef2d4f6e88e3bf5cee50e603
* https://sketchfab.com/3d-models/ball-of-rope-879d66b3d3df4fa28b3fe92f5493261f
* https://sketchfab.com/3d-models/rope-595ba22ff67b49e0b2b33225a6f2db1c
* https://sketchfab.com/3d-models/rope-coil-ca2aadea0c624291a464a544984eced5

**4: mortar bucket**
* the collection above has a low poly bucket, but it looks like metal, might need to be recoloured to black to indicate it is silicone?
* this tool collection has a black one: https://sketchfab.com/3d-models/low-poly-tools-pack-b7892e52af474dffaf00a974aa974940
* alternative: https://sketchfab.com/3d-models/bucket-5-74fe4c4910da407094d211fef2d34f01

**5: masonry hammer**
* which of these? https://sketchfab.com/3d-models/hammers-pack-9a44ad797f9642e3aa40a98783e76514
* or from low poly tool set: https://sketchfab.com/3d-models/50-low-poly-tools-3453c7da36834a8d81efdb93fed6d466
* or from this low poly set: https://sketchfab.com/3d-models/low-poly-tools-pack-b7892e52af474dffaf00a974aa974940

**6: trowel**
* https://sketchfab.com/3d-models/trowel-051130eff8de45238b69dc4fa484af43
* https://sketchfab.com/3d-models/smoothing-trowel-5ad72c4423cd41a6a6d3df2de46fdb8f
* https://sketchfab.com/3d-models/simple-trowel-69621d5e60ba44a5bea1d537c5442b6f
* https://sketchfab.com/3d-models/gauging-plastering-trowel-72cfa8e9c4d24390ba6ba78ab279b9c4
* https://sketchfab.com/3d-models/trowel-6846e18687c1430d88260c8a2e33e5a9
* https://sketchfab.com/3d-models/smoothing-trowel-5ad72c4423cd41a6a6d3df2de46fdb8f
* https://sketchfab.com/3d-models/trowel-051130eff8de45238b69dc4fa484af43
* Industrial tool pack (spatula, trowel, several smoothing trowels): https://sketchfab.com/3d-models/industrial-tool-pack-305e180a472340209673fa485445dc8e

**7: spirit level**
* https://sketchfab.com/3d-models/50-low-poly-tools-3453c7da36834a8d81efdb93fed6d466
* https://sketchfab.com/3d-models/spirit-level-6463b75b20c347e9b23f8c9a1eb24fbc
* https://sketchfab.com/3d-models/spirit-level-5254b4faa30045febd1b34ac56a74be2
* https://sketchfab.com/3d-models/spirit-level-8ee23876d8c944799086e3982b4edd3f

**8: set squares**
* https://sketchfab.com/3d-models/set-squares-ca788117142a47b783237a0507dce6a0
* in low poly collection 1: https://sketchfab.com/3d-models/50-low-poly-tools-3453c7da36834a8d81efdb93fed6d466
* in low poly collection 2: https://sketchfab.com/3d-models/low-poly-tools-pack-b7892e52af474dffaf00a974aa974940
* wooden handle: https://sketchfab.com/3d-models/set-square-3e2574df68d94aaeb849f5ce4d073a39
* ruler/spirit level/set quare combi tool: https://sketchfab.com/3d-models/ruler-and-set-square-d25a8929ad114079a88aab271d46eaa6

**9: straightedge / featheredge / levelling gauge**
* cannot find, only related tools
* bevel gauge: https://sketchfab.com/3d-models/bevel-gauge-93bfec3a68214dc5ba44f225698a5af5
* vibratory screed: https://sketchfab.com/3d-models/vibratory-screed-4c6755845f2740a68e97d26219078301

**10: shovel**
* https://sketchfab.com/3d-models/low-poly-heavy-tools-02a7b83130e141218927f11d90570904
* in collection 1
* in collection 2
* in collection 3
* with wheelbarrow and cement mixer: https://sketchfab.com/3d-models/3-low-poly-mixer-wheelbarrow-shovel-fa1c464134d1458cb9210e7e3f8571f5

**11: wheelbarrow**
* https://sketchfab.com/3d-models/low-poly-cartoon-wheelbarrow-7b71913293ff4864bcaeb4e3c1d3549f
* https://sketchfab.com/3d-models/3-low-poly-mixer-wheelbarrow-shovel-fa1c464134d1458cb9210e7e3f8571f5
* https://sketchfab.com/3d-models/wheelbarrow-baked-low-poly-23-576005f6bcbf4983b92e91da5a1b6c3e

**Comment by fwild** [comment]
3: Maurerschnur: rot, aufgerollt mit haspel

<img width="1030" alt="Screenshot 2023-05-11 at 15 28 44" src="https://github.com/WEKIT-ECS/MIRAGE-XR/assets/183296/7978d101-08ab-4f58-81a9-be51c9786ea1">

**Comment by fwild** [comment]
hammer: https://www.amazon.co.uk/Stanley-1-54-022-FatMax-AntiVibe-Hammer/dp/B000X29ENO/ref=asc_df_B000X29ENO/?tag=googshopuk-21&linkCode=df0&hvadid=208050023643&hvpos=&hvnetw=g&hvrand=11598795580531985623&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9046127&hvtargid=pla-422856396421&psc=1&th=1&psc=1

**Comment by fwild** [comment]
Maurerkelle: https://sketchfab.com/3d-models/trowel-6846e18687c1430d88260c8a2e33e5a9

**Comment by fwild** [comment]
spirit level: should it be functional and show that it is level?

**Comment by fwild** [comment]
Maurerwinkel: einfacher stahlwinkel

**Comment by fwild** [comment]
8: set squares: 50cm x 30cm
![Screenshot 2023-05-11 at 15 42 07](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/183296/8f031a0d-83f1-4a9b-a437-48e33647ffb2)

**Comment by fwild** [comment]
Fugenkelle:
![Screenshot 2023-05-11 at 15 41 15](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/183296/2add155f-2db6-4251-9f94-6875d4a7a784)

9: Richtscheit: 2m aluminium blade
http://www.jradcliffeplant.co.uk/concreting-equipment/straight-edges

**Comment by fwild** [comment]
Shovel: https://sketchfab.com/3d-models/3-low-poly-mixer-wheelbarrow-shovel-fa1c464134d1458cb9210e7e3f8571f5

**Comment by fwild** [comment]
wheelbarrow: 
https://sketchfab.com/3d-models/3-low-poly-mixer-wheelbarrow-shovel-fa1c464134d1458cb9210e7e3f8571f5

**Comment by fwild** [comment]
More collections (not selected):
* https://sketchfab.com/3d-models/meld-tec-workbench-5d2a15edceec44c79e0aa6ef754a70e5
* https://sketchfab.com/3d-models/construction-objects-2488760f37244517b07d2f011e77f282

**Comment by fwild** [comment]
1: ruler:
https://sketchfab.com/3d-models/construction-measuring-tapes-ruler-867f2f15d871459689fe6e43033d0ac6

**Comment by fwild** [comment]
4: bucket:
https://sketchfab.com/3d-models/low-poly-tools-pack-b7892e52af474dffaf00a974aa974940

**Comment by fominykh** [comment]
@jafarigit are you still working on this?
