### ISSUE TITLE
Remove the Search button from the bottom panel on all screens except the Home/Activity screen

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1338]

**Comment by Alvareon** [comment]
https://github.com/WEKIT-ECS/MIRAGE-XR/pull/1363

**Comment by fwild** [comment]
I think this is done everywhere - cannot find any other appearance?

**Comment by fominykh** [comment]
yes, done https://github.com/WEKIT-ECS/MIRAGE-XR/pull/1363
