### ISSUE TITLE
Design for settings in profile on mobile platforms

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#1393]
Add design proposal to separate out the settings from the login information.

**Comment by fominykh** [comment]
Waiting for feedback:
![image](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/10297277/878e9278-f324-45a6-a928-08e9c115baa1)

**Comment by fominykh** [comment]
Almost done. Getting ready for implementation: https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1867

**Comment by fominykh** [comment]
To be able to finish the Registration UX and UI, we are waiting for progress with SSO, some or all of these issues:
https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1885
https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1832
https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1831
https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1228
... or requirements for what the registration screen should contain.
