### ISSUE TITLE
Snap to Grid: GridManager - settings for the grid.

### ISSUE THREAD

**Issue by cawke** [WEKIT-ECS/MIRAGE-XR#1403]
https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1327

- allow to set grid size globally in profile > group: preferences
- allow to set rotation angles globally in profile > group: preferences
- standard size: 5 cm
- standard grid angle: 0 degrees

**Comment by fwild** [comment]
set standard size for angles to 15 degrees.
