### ISSUE TITLE
Floor Detection: find surface animation 

### ISSUE THREAD

**Issue by cawke** [WEKIT-ECS/MIRAGE-XR#1409]
will be enough just a picture of a hand with a phone.

![image](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/20320355/4df3ac00-c534-4a34-8487-f6f7d6756707)

example: https://developers.google.com/ar/design/assets/findingasurface.gif

**Comment by fominykh** [comment]
Design source in Figma
![image](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/10297277/a59b91b9-30c3-4f7e-ace1-e6e2ebb899f4)
