### ISSUE TITLE
SpatialMapManager NRE

### ISSUE THREAD

**Issue by robhillman97** [WEKIT-ECS/MIRAGE-XR#1413]
The UpdateSpatialMapColiders method in SpatialMapManager throws an NRE when deployed on a hololens. It appears to happen when looking for the "Spatial Awareness System" game object before it is instantiated. Try catch has been added to prevent the NRE but needs to be fixed to prevent unxpected behavior.

**Comment by fwild** [comment]
I think this might be connected to this: the character model used to have detection of the floor plan, so when you move the boundary box close to the floor plane, the character model would bounce up and down to indicate it is 'locked' to the floor plane. This is no longer the case? And: I think the aura is below the floor, further down than it used to be (could also be lighting here in my room - it is evening)?

**Comment by fwild** [comment]
Actually: I switched the light on and now it bounces nicely, the floor plane is definitely detected.

**Comment by fwild** [comment]
I am not sure that we would be using the spatial awareness system at the moment at all, to be honest. I think this may be a remnant of experiments?

**Comment by fwild** [comment]
The aura is still below the floor, though. I will log that as a separate one.
