### ISSUE TITLE
App is generally slow 

### ISSUE THREAD

**Issue by robhillman97** [WEKIT-ECS/MIRAGE-XR#1419]
On hololens the app feels slow and takes a while to load activities, add steps, etc.. Also all elements briefly sometimes turn off and on when using UI elements .

**Comment by robhillman97** [comment]
Could be related to having the console window open. We have a few big debug logs which may not be needed

**Comment by fwild** [comment]
Yes, pretty sure that is the debug log - that's what usually happened in the past as well!
