### ISSUE TITLE
Cloud upload: improve update or clone message

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1420]
The text should be corrected to 
"The activity you are trying to upload already exists on the server. Please select an option:"
![image](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/10297277/168d64e2-256b-45b0-ae92-5d993a7d5b48)

**Comment by fwild** [comment]
About the timing: it takes a long time to upload, if you have some media in your activity, so I think what happened is rather that the upload finished, while you already had navigated away from the page...? To fix this, we should add some upload progress bar, in my view. Maybe even a blocking progress bar?

**Comment by fwild** [comment]
I am editing this ticket and will split off the ticket about progress bar.
