### ISSUE TITLE
Diamond, augmentations, and spawning sphere appear behind the yellow stripe

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1421]
Bug:
Often, the diamond, augmentations, and the spawning sphere - all appear behind the yellow stripe. When this happens, the augmentation is not possible to edit or move.

![image](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/10297277/29b6e43d-e952-4738-8f61-0b856fb9db35)

**Comment by fwild** [comment]
And could we add some opacity effect on the band, please? Or do something cooler with the band running across the spatial map?

**Comment by fominykh** [comment]
![Screenshot_20230622_164642_MirageXR.jpg](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/10297277/499b9fb3-4354-46ae-b447-48d65d7121c2)

![Screenshot_20230622_164716_MirageXR.jpg](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/10297277/126065c7-df8d-4ca9-8670-9ed7d219fbf4)

![Screenshot_20230622_164848_MirageXR.jpg](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/10297277/a2eddd37-5471-44ba-b5f5-66a0eca10718)

**Comment by fominykh** [comment]
This issue is becoming a real problem. It is hard to test, because I cannot move the task station diamonds. I guess the reason is that the diamond spawns very close to the floor. Or the aura jumps up and down and this causes the diamond to move.
I also observed that the task station diamond moves to a random position from time to time, maybe because the tracking is lost.

**Comment by fwild** [comment]
Resolved by removing the ribbon. closing.
