### ISSUE TITLE
Tutorial: Refactor Tutorial Manager

### ISSUE THREAD

**Issue by BorisJov** [WEKIT-ECS/MIRAGE-XR#1472]
Over time, the Tutorial Manager has grown quite a bit. While the overall architecture works, there are some legacy bits of code that need to be refactored. Then, an easier and more consistent TM can be used.

The refactoring should take into account that we might want to load tutorials dynamically at run-time, so that we can search for templates, download them, and share.

**Comment by fwild** [comment]
@cawke can you state your input, please? what you had in mind?

**Comment by BorisJov** [comment]
The Tutorial Manager now has a new version and is almost completely refactored. Only AR UI parts remain. Closing issue
