### ISSUE TITLE
Bug: saving as guest, opening after login

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1474]
How to reproduce:
1. Open v.2.2.1 from the store
2. Enter as a guest
3. Create an activity "Activity (22/06/2023 15:38:06)"
4. Add Action augmentation "checkmark".
5. Close the app.
6. Open the app again, login.
7. Observe that the created activity is in the list of activities.
8. Open the activity "Activity (22/06/2023 15:38:06)"
9. Observe that the list of augmentations is empty.
10. Select edit step and tap on "Add augmentation"
11. Observe that the library of Action glyphs does not appear. Instead, a "checkmark" appears in the list immediately.

**Comment by fwild** [comment]
Workaround: explicitly "publish..." to local, then it will be saved. I think an event is missing here that persists the data model?

**Comment by fwild** [comment]
Superseded by: https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1570
closing.
