### ISSUE TITLE
+/- buttons for audio aug 3D radius missing

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#1493]
files for the buttons are either not linked or missing from project:
![image](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/183296/a4105431-7fa5-4f63-a75f-08c0753cb084)

**Comment by Alvareon** [comment]
https://github.com/WEKIT-ECS/MIRAGE-XR/pull/1498
