### ISSUE TITLE
mobile: image and video aug: orientation not settable

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#1494]
Orientation from gallery pics is not set with button, but always set to portrait. Update: same applies to new photos, and to videos (no matter whether gallery or photo).

And please move the preview image a few pixels down, there is a small video see-through strip visible, which looks weird.

**Comment by Alvareon** [comment]
Fixed: https://github.com/WEKIT-ECS/MIRAGE-XR/pull/1499

![photo1688500268 (1)](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/34060044/2ff63be9-9a85-4c86-a7b2-e0351eef2ac3)
![photo1688500268](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/34060044/0e69d0c8-c1b4-4841-85d9-8c7d9cf67cb9)
