### ISSUE TITLE
mobile: label: gaze trigger not working / edited values not stored

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#1496]
The gaze trigger functionality is not evaluated, nothing happens when focusing on the label in view mode. Moreover, the values set (duration, which step) are not updated when re-entering the edit panel, and set to the last index value each.

Update: when I restart the app, it actually works to evaluate for a new activity and new label, but only if I don't select a step. Once I change the step to jump to, I get a NullReferenceException: Object reference not set to an instance of an object. Which then makes the label aug crash in view mode, too.

To reproduce:
create new activity, create second step, go back to step 1 and add label augmentation, text = "test", gaze trigger on, reduce duration to 1 sec, select step 2 (= null reference exeption). Accept and switch to view mode: label trigger not working.

**Comment by Alvareon** [comment]
https://github.com/WEKIT-ECS/MIRAGE-XR/pull/1500
