### ISSUE TITLE
Update GLTF plugin  

### ISSUE THREAD

**Issue by cawke** [WEKIT-ECS/MIRAGE-XR#1518]
The [library](https://github.com/Siccity/GLTFUtility) we used to import gltf models has not been updated for a long time (Jan 20, 2021). it would be good to replace it with another [library](https://github.com/atteneder/glTFast).

**Comment by fwild** [comment]
Related tickets (first one has cool test cases for VERY advanced glTF functionality!): https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1286 https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1613
