### ISSUE TITLE
Design the color selector screen for mobile UI

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1542]
Currently:
The new color selector screen is implemented. (screenshot required @robhillman97 )

Should be:
The mobile UI design should be made for this screen.

**Comment by robhillman97** [comment]
![Untitled](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/65968011/d2e542b1-14d2-4a7b-b742-0a607330f3cb)

**Comment by fominykh** [comment]
@robhillman97 it looks like the color picker you used contains 2 yellow colors tgatare exactly the same.

**Comment by fominykh** [comment]
Final design is ready in Figma
![Adding Label_06](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/10297277/cf64a62c-5a61-49b3-ae37-70919f45c0d7)
