### ISSUE TITLE
Design the Label settings screen mobile UI

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1543]
Currently:
The new Label settings screen is implemented. (screenshot required @robhillman97 )

Should be:
The mobile UI design should be made for this screen.

**Comment by robhillman97** [comment]
![Untitled](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/65968011/8b7b8a58-c21c-48e3-be6d-8c8f0076baf7)

**Comment by robhillman97** [comment]
![Untitled](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/65968011/2b2f3e84-e71e-43b3-8317-910101e5d492)

**Comment by fominykh** [comment]
@robhillman97 
Why did you put these settings on a separate screen? Can we add these settings to the main label edit screen between the text edit field and the Gaze settings?

**Comment by robhillman97** [comment]
I added this on a separate screen as I felt they would make the main label editor screen too busy. The label preview in particular can take up a lot of space, if no text is entered it will say "Preview label text" but if the user has entered their text before moving to this screen it will update to show the inputted text and change size accordingly

**Comment by fominykh** [comment]
Final design is ready in Figma
![-5447268594900651222_120](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/10297277/34b6a15b-1c06-4dae-af52-33bdeeb8cc31)
