### ISSUE TITLE
UI : Label - TextField

### ISSUE THREAD

**Issue by KheireddineAzzez** [WEKIT-ECS/MIRAGE-XR#1564]
Hi,
When we include multiple TextFields in a step, it becomes challenging to identify the specific text we intend to modify or remove.

It is better, that   the user is able to specify the Label name: 
[Class Label](https://github.com/WEKIT-ECS/MIRAGE-XR/blob/627f530fc75379e06a57c82a0476a9388580a8c2/Assets/MirageXR/Player/Scripts/Augmentations/Label/Label.cs)

![Lable](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/59838139/acb6e65a-e764-4b50-aea2-ecbd98902d19)

**Comment by fwild** [comment]
Duplicate of https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1249
