### ISSUE TITLE
Gaze trigger for the Action augmentations is not saved and does not work

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1565]
dupe of #1580 
I tested v 2.3 on iOS and Android, the behavior is the same.
1. I create a new activity with 2 steps.
2. Add action augmentation to step 1.
3. Select gaze trigger.
4. Save activity locally.
5. Open to play and observe no gaze.
6. Open to edit and observe the gaze checkbox OFF.

**Comment by robhillman97** [comment]
Currently edits to an action augmentations settings are only saved if the user re-selects the action from the list. Tapping the close button will not save the changed settings. We should find a better solution to this to improve UX.

**Comment by fwild** [comment]
-> Implement the new UI
