### ISSUE TITLE
The Jump-to-Step Function of the Label

### ISSUE THREAD

**Issue by KheireddineAzzez** [WEKIT-ECS/MIRAGE-XR#1575]
**Hardware:** iPad Pro + Lidar Sensor + Cellular
**Application:** MirageXR, Version 2.4

**Issue Description:**

**Steps to Reproduce:**
1. Open MirageXR on an iPad Pro equipped with a Lidar sensor and cellular connectivity.
2. Create a new activity.
3. Within the activity, add a step named "Step2."
4. Inside "Step2," create three labels named Label1, Label2, and Label3.
5. Next, add another step named "Step3."
6. Edit Label1 and Label2 to utilize the Gazing function, with a jump-to-step function assigned to "Step3."
7. Now, add another step called "Step4."
8. Edit Label3 to employ the Gazing function, with a jump-to-step function assigned to "Step4."

**Issue:**
Despite setting Label3's jump-to-step function to "Step4," it still directs to "Step3" when gazed upon. The expected behavior is for Label3 to transition to "Step4."

**Expected Behavior:**
Label3, when employing the Gazing function, should correctly transition to "Step4," in line with the assigned jump-to-step function.

**Comment by fwild** [comment]
Seems to be fixed in 2.4 (android) - but needs rechecking!

**Comment by fwild** [comment]
Fixed with current release in both Apple app store and Google Play store. Closing.
