### ISSUE TITLE
Markers: make more flexible

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#158]
In GitLab by @fwild on Nov 16, 2020, 11:45

3 scenarios:
- calibrate once for all activities (the Mars rover case): new ticket: https://platform.xr4all.eu/wekit-ecs/mirage-xr/-/issues/594
- don't calibrate at all, but allow manual placement or automated placement of objects based on their space requirements (the digital twin case)
- calibrate in each activity (and describe how to place the physical marker as part of the activity: take photo and describe with text how to do it)

**Comment by wekitecs** [comment]
In GitLab by @fwild on Nov 16, 2020, 11:46

or maybe try out the vuforia model recognition

**Comment by wekitecs** [comment]
In GitLab by @william.guest on Dec 17, 2020, 19:38

i am currently investigating options for 3D model markers and any new (2020) pipelines for markers based on captured images.

**Comment by wekitecs** [comment]
In GitLab by @wild on Jan 28, 2021, 15:22

The last bullet point is already a ticket on its own: https://platform.xr4all.eu/wekit-ecs/mirage-xr/issues/147

**Comment by wekitecs** [comment]
In GitLab by @william.guest on Jan 28, 2021, 15:26

Consider calibrating per-space rather than per-activity. Also manual placement of an origin.

**Comment by wekitecs** [comment]
In GitLab by @wild on Feb 16, 2021, 17:47

Would be cool to try and lay out the whole activity (orient, maybe even resize) according to the space available from the spatial map - for those activities where the task station locations are marked as "flexible" (or some such).

**Comment by wekitecs** [comment]
In GitLab by @wild on Feb 24, 2021, 12:52

Option 3 is a separate ticket and being worked on. Moving the rest to Sprint 6, as related to Spatial Understanding tickets.

**Comment by wekitecs** [comment]
In GitLab by @a85jafari on Feb 25, 2021, 22:16

Why we do not just set the origin as the player position with z = 0 (y in Unity) . We can ask the player to press a button when ready to calibrate the activity or whatever.

**Comment by wekitecs** [comment]
In GitLab by @wild on Feb 26, 2021, 14:15

A good use case to keep in mind is that this is to transfer content recorded on one airplane to a second airplane of the same model in a different hangar.

**Comment by wekitecs** [comment]
In GitLab by @a85jafari on Apr 15, 2021, 19:56

removed milestone

**Comment by fwild** [comment]
This has been broken into separate tickets, closing.
