### ISSUE TITLE
tool for tracking situations where the tracker is lost in space.

### ISSUE THREAD

**Issue by cawke** [WEKIT-ECS/MIRAGE-XR#1587]
If tracking is lost, the user will be shown a popup or toast asking to recalibrate.

**Comment by fwild** [comment]
Good solution. I am wondering, if tracking can recover as well, by moving back to last position where it worked? And adding this to the toast or popup message as well?

**Comment by fwild** [comment]
From discussion with Mikhail I understand that the main problem is, that system may loose tracking of the origin anchor, but still sees current anchor of current augmentations - so when calculating the relative offset from origin, it does not save the values. Interesting question: can't we calculate the positions relative from the task station instead? This may be more stable?

**Comment by fwild** [comment]
Can you release a test version with the popup or toast message for us, so we can check if that's the mother of all calibration problems?

**Comment by fwild** [comment]
Linked ticket: https://github.com/WEKIT-ECS/MIRAGE-XR/issues/411
