### ISSUE TITLE
Add Alien and Students Animation for PBIS

### ISSUE THREAD

**Issue by MariellaF** [WEKIT-ECS/MIRAGE-XR#1588]
Add animations related to the alien and students. These animations can be applied to implement behavior in PBIS use cases.

**Comment by fwild** [comment]
Please give a shout if you need any support on merging this back as a pull request!

**Comment by MariellaF** [comment]
Hi Fridolin, thank you for your availability. I am waiting for Giuseppe to test the animations and then I am ready to make the merge request. I will update you as soon as we are done.
