### ISSUE TITLE
Labels in old activities are displayed without text and cannot be edited

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1649]
Installed the most recent Test Flight version of the eROBSON app.
I opened an activity created in eROBSON app in July 2023 "eR 03 basics of IoT (13/07/2023).
The activity contains labels. The labels are just orange. They do not display text. And they cannot be edited anymore.

**Comment by fwild** [comment]
If there were eRobson specific additions to the data model, it might be that the latest additions (for font size and colour) of the label data were not merged correctly when merging develop back into the eRobson branch?

**Comment by jafarigit** [comment]
The issue are solved in the new test flight build 33
