### ISSUE TITLE
Lock checkbox for every bit

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1650]
We need a lock chckbox for every bit to lock the movement of the bit augmentations when the user taps on them.

Currently only bits that have two parts connected by a wire have a Lock checkbox. 
We need a lock checkbox for all bits. We need it to be able to lock the bits in space and avoid accidentally moving them or disconnecting them.

It is important that:
- if two little bits are connected AND both are locked, it should not be possible to disconnect them.
- if a bit is locked, it should still be possible to interact with its interactable part, e.g., the slider on the Slide dimmer bit.
- If one bit is locked, it should be possible to connect another bit to it or disconnect another bit from it.

**Comment by jafarigit** [comment]
The global lock system is applied to eRobson too.
