### ISSUE TITLE
Add function to the o6 Busser Bit

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1654]
Currently,
The o6 Busser bit does not have a function - other bits can interact with is only by snapping (and possibly transmitting power).

Should be:
The buzzer converts the electrical signal it receives into a vibration, which creates a buzzing sound. The higher the signal it receives, the more intense the vibration, and the louder the sound. https://classroom.littlebits.com/bit-o-pedia/buzzer

The function of the Buzzer is similar to the Lamp. But instead of the light intensity of the Lamp, the buzzer changes the volume of the sound.

**Comment by jafarigit** [comment]
Done

**Comment by fominykh** [comment]
Tested in v 2.3.151 (32), and it works.
