### ISSUE TITLE
Add function to the o9 Bargraph bit

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1655]
Currently,
The o9 Bargraph bit does not have a function - other bits can interact with is only by snapping (and possibly transmitting power).

Should be:
The o9 Bargraph bit
Description and video demonstration are here: https://classroom.littlebits.com/bit-o-pedia/bargraph

Bargraph has 5 small led lamps. The more power the bargraph gets, the more lamps will light up.

Each lamp can light in different colors, but we can make a simplified version where only green light is used.
![image](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/10297277/ae94fadf-d095-444c-aece-c1ccd4b78fcd)

**Comment by jafarigit** [comment]
Done

**Comment by fominykh** [comment]
Tested in v 2.3.151 (32), and it works.
