### ISSUE TITLE
Branch bit is snapped incorrectly

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1657]
![image](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/10297277/349237ff-dc89-49b3-b735-8739a2a6737f)

**Comment by jafarigit** [comment]
As the arrows show, the power only can be connected from one side which is the bottom one in this screenshot

**Comment by jafarigit** [comment]
Fixed
