### ISSUE TITLE
Enable rotation of the bit augmentations

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1658]
Currently,

All bits spawn in the correct rotation, and it is impossible to rotate them.

Should be:

It should be possible to rotate bits by 90 degrees (Grid can be used with a setting 90 degrees).

In the situation when the bits always spawn in the correct orientation, one of the learning goals - to correctly position the bits - cannot be achieved. Therefore, it is important.

Rotation is also required for the Branch bit to work.

**Comment by jafarigit** [comment]
Solved
