### ISSUE TITLE
Re-connecting earlier connected bits

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1668]
Currently,

In edit mode, 
1. Add two steps.
2. Add two bits (which are possible to connect to each other) with keep alive 1-2.
3. Save.

In Play mode,
1. On step 1 connect the two bits (Bit A and Bit B).
2. On step 2, the bits will appear connected.
3. If the user moves Bit A away (disconnects by moving only bit A and not touching bit B), it is impossible to connect bit A back to bit B.
4. If the user moves both bit A and bit B, they can be connected again.

It should be possible to re-connect bits by moving only one of them away and later back.

**Comment by jafarigit** [comment]
It is not very clear for me what the issue exactly is! Can you record a video?

**Comment by jafarigit** [comment]
Issue is fixed
