### ISSUE TITLE
Design 3D letters for a library

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1678]
Requested in ARIDLL.

Can we design 3D letters that can:
1. Be white by default but can change texture to any solid color?
2. Snap to each other on the left or right so that the users can play with them (like we snap bits in eROBSON)?

@jafarigit and @fwild what do you think?

Example letters:
https://sketchfab.com/andre.arancibia/collections/letters-d5b344a91ea94ba283ee07b2955e7810

**Comment by KheireddineAzzez** [comment]
In reference to @fominykh  's recent suggestion, the production method for creating uppercase alphabetical letters is as follows:

Production Steps:
1. Use the "jungle" font and set the text color to white.
2. Convert the text into a mesh.
3. Separate by  loose parts 
4. Extrude the resulting objects.
5. Set the letter origins into geometric points.
6. Apply the Decimate operation with the Planar option.
7. Export the final objects as an STL file in Batch Mode.

You can find the collection contains some  uppercase alphabetical letters here: [Link](https://sketchfab.com/HHN_UnityLab/collections/uppercase-alphabetical-letter-0b1a0da3c33b42f29e5c177d6e6d8564)

 @fwild

**Comment by fominykh** [comment]
@fwild what do you think? Shall we turn this to a library?

**Comment by fominykh** [comment]
The design is ready. Implementation issue: https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1869
