### ISSUE TITLE
eROBSON bug: button and fan bits do not work together )one of them is broken)

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1684]
How to reproduce,

1. Start eROBSON Test flight version of MirageXR on iPad .
2. Add power source, USB power, button, and fan.
3. Connect Power source, USB power, and fan directly. Observe that the fan works as expected.
4. Connect Power source, USB power, button, and fan. Observe that the fan does not get the green indicator ON and does not rotate when the button is pressed. At the same time, when the button is OFF, the fan spins.

**Comment by jafarigit** [comment]
I have tested this issue on both Android and iOS and seems works fine on both. probably the tested build had the issue. I will close this issue and can be reopen if it happened again

**Comment by fominykh** [comment]
Tested in v 2.3.151 (32), and it works.
