### ISSUE TITLE
Update replacing file dialog message

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1715]
There is a typo in the dialog message "This file is exist! Please select an option:"
The message should be "The activity you are trying to save already exists in the cloud. Please, select"

https://github.com/WEKIT-ECS/MIRAGE-XR/blob/402576264199c8aca79fc34ac57ef9c31d7ea55f/Assets/MirageXR/Player/Scripts/Mobile/StepsListView.cs#L225

https://github.com/WEKIT-ECS/MIRAGE-XR/blob/402576264199c8aca79fc34ac57ef9c31d7ea55f/Assets/MirageXR/Player/Scripts/ActionListMenu/ActivityEditor.cs#L111

https://github.com/WEKIT-ECS/MIRAGE-XR/blob/402576264199c8aca79fc34ac57ef9c31d7ea55f/Documentation/html/_activity_editor_8cs_source.html#L196

https://github.com/WEKIT-ECS/MIRAGE-XR/blob/402576264199c8aca79fc34ac57ef9c31d7ea55f/Documentation/html/_steps_list_view_8cs_source.html#L315

https://github.com/WEKIT-ECS/MIRAGE-XR/blob/402576264199c8aca79fc34ac57ef9c31d7ea55f/Assets/MirageXR/Tests/NewUI/ActivitySettings.cs#L226

**Comment by fwild** [comment]
in RC2.5? because since 2.4, I have edited this message, I thought ..

**Comment by fominykh** [comment]
OK, maybe it is resolved then. I found it in the eROBSOn version, pulled from develop a month ago.

**Comment by fwild** [comment]
text was too long, updated it now. not sure whether the legacy StepsListView.cs is used anymore (isn't it replaced by _v2.cs?), but I changed it there too.
