### ISSUE TITLE
3D model does not snap to grid for position change with 1st placement

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#1744]
To reproduce: add a new activity, add 3D model to step, select apple; observe that the position does not snap to grid.
Work around: switch to play mode, and switch back to edit mode; observe that the position does now snap to grid.

**Comment by fwild** [comment]
May be related to the size not changing bug?

**Comment by fwild** [comment]
Seems not to happen on iPad! Only on Android?

**Comment by fwild** [comment]
Update: seems only to affect library items! (tested with the apple)

**Comment by cawke** [comment]
I can't replicate it. 
Did you calibrate before creating the 3d model?
Without calibration, the snap to grid doesn't work.

**Comment by fwild** [comment]
This was only for library items, not sketchfab items. This is resolved now.
