### ISSUE TITLE
Task station diamond: make configurable

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#1806]
Often users place the diamond too far away or too close - why not make the diamond configurable with a toggle, also allowing to set its size, or maybe offer a couple of alternative visualisations (portal, flat floor marker launch symbol, flat book marker launch symbol)?

Related to: https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1539

**Comment by fwild** [comment]
@fedfomi, @fominykh what do you think?

**Comment by fominykh** [comment]
After March 21, we can get on this task.
We are redesigning the task station completely, I assume, not only the diamond.

**Comment by fominykh** [comment]
Design is ready. A toggle element is needed.

![Image](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/10297277/dac9b2a1-26e8-4903-8dac-79f72634eb8f)

**Comment by fwild** [comment]
Where to find the task station attachment code https://github.com/WEKIT-ECS/MIRAGE-XR/pull/1805
