### ISSUE TITLE
Repo: R2: Refactor data model

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#1834]
Revise ARLEM data model (activity, workplace) to become compatible with real-time graph-based manipulation

**Comment by fwild** [comment]
Implemented and now in lib-lee

**Comment by cawke** [comment]
the new data model has a more flexible architecture and avoids data duplication compared to the old one, which allows us to implement features such as:
- switching steps
- activating one content for several steps
- adding elements of the step hierarchy
- adding comments
- adding tools
- expanding work with users as entities
- simplifying synchronization and work with content files
- simplifying the implementation of basic functions such as adding/removing content/step
- allowing you to expand different types of content with custom fields
