### ISSUE TITLE
Discussion and conceptual design of naming augmentations

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1918]
Currently,
The augmentations are named automatically.
In the mobile UX design, we foresee a screen just before the augmentation is created where the author can give augmentation a name. This adds another screen increasing the length of the process.
There is also an already implemented function to rename an augmentation, available via the augmentation settings.

Questions:
Should we name augmentations automatically and allow to rename?
Or should we include an extra screen asking the author to name each augmentation?
One alternative is to place two buttons at the bottom of the screens for adding augmentations: 
- one of the buttons will bring up another screen to name the augmentation
- the other one will skip the naming step 
![image](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/10297277/1e66a611-191a-486f-bcf3-3fe71f08ac24)

**Comment by fwild** [comment]
We could put a text field on this screen, with

```
Name:
“Automatically named, e.g. model file name”
Apply
```

so the user can modify before accepting,
And leave the rename functionality in the
Context menu as is?

**Comment by fominykh** [comment]
Good idea!

**Comment by fominykh** [comment]
Decided on editable title and an effort to make meaningful automatically generated titles.
