### ISSUE TITLE
add ISO warnings to model library

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#1925]
Move all warnings to the model library, as separate groups.

- [x] “ISO 7010 - Safety”: [E-signs.zip](https://github.com/WEKIT-ECS/MIRAGE-XR/files/14952181/E-signs.zip)

- [x] “ISO 7010 - Fire”: [F-signs.zip](https://github.com/WEKIT-ECS/MIRAGE-XR/files/14952182/F-signs.zip)

- [x] “ISO 7010 - Mandatory”: [M-signs.zip](https://github.com/WEKIT-ECS/MIRAGE-XR/files/14952183/M-signs.zip)

- [x] “ISO 7010 - Prohibition”: [P-signs.zip](https://github.com/WEKIT-ECS/MIRAGE-XR/files/14952184/P-signs.zip)

- [x] “ISO 7010 - Warning”: [W-signs.zip](https://github.com/WEKIT-ECS/MIRAGE-XR/files/14959744/W-signs.zip)

Then remove all `Assets/MirageXR/ContentTypes/Warning/SymbolSprites/*.png` and delete the player-only warning augmentation code.

**Comment by fwild** [comment]
The symbols are free (wikimedia): 
https://commons.wikimedia.org/wiki/Category:ISO_7010_safety_signs_%28vector_drawings%29

I quite like the aesthetics of this:
https://www.thingiverse.com/thing:4830734

**Comment by fwild** [comment]
“ISO 7010 - Safety”: [E-signs.zip](https://github.com/WEKIT-ECS/MIRAGE-XR/files/14952181/E-signs.zip)

“ISO 7010 - Fire”: [F-signs.zip](https://github.com/WEKIT-ECS/MIRAGE-XR/files/14952182/F-signs.zip)

“ISO 7010 - Mandatory”: [M-signs.zip](https://github.com/WEKIT-ECS/MIRAGE-XR/files/14952183/M-signs.zip)

“ISO 7010 - Prohibition”: [P-signs.zip](https://github.com/WEKIT-ECS/MIRAGE-XR/files/14952184/P-signs.zip)

“ISO 7010 - Warning”: [W-signs.zip](https://github.com/WEKIT-ECS/MIRAGE-XR/files/14959744/W-signs.zip)

**Comment by Alvareon** [comment]
https://github.com/WEKIT-ECS/MIRAGE-XR/pull/2203
