### ISSUE TITLE
Incomplete Object Removal in Scene Transition

### ISSUE THREAD

**Issue by KheireddineAzzez** [WEKIT-ECS/MIRAGE-XR#1941]
Hi,
It would be nice if all objects from the scene were removed after closing the activity because the objects from the previous activity are still on the scene

**Comment by fwild** [comment]
Can you refine? You mean that when you go back to the list of activities, the current activity is still open (up until you open a new one or create a new one), right?

**Comment by KheireddineAzzez** [comment]
when i go back to the list of activities, the objects of the recent opened activity still in scene

**Comment by fwild** [comment]
This is a design choice, maybe requiring better UI guidance that the user is still in an activity. Closing it.
