### ISSUE TITLE
Find a solution to replace HTK TextToSpeech

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#20]
In GitLab by @BenediktHensen on Jul 4, 2020, 17:33

The HTK TextToSpeech component does not exist anymore in MRTK because it is not cross-platform compatible. We need to find an adequate replacement.

**Comment by wekitecs** [comment]
In GitLab by @BenediktHensen on Jul 4, 2020, 17:34

changes affect:

* [x] Assets\WEKIT\Player\Scripts\Managers\Maggie.cs

**Comment by wekitecs** [comment]
In GitLab by @BenediktHensen on Jul 15, 2020, 19:47

mentioned in commit 711eff2a3de6995426f32b6732a8822cf03a9495

**Comment by wekitecs** [comment]
In GitLab by @BenediktHensen on Jul 15, 2020, 19:50

I re-added the TextToSpeech file of the HTK. According to https://github.com/microsoft/MixedRealityToolkit-Unity/issues/3569 it is working on the HoloLens but for cross-platform support we need a solution that adapts to each platform.

**Comment by wekitecs** [comment]
In GitLab by @BenediktHensen on Jul 15, 2020, 19:50

unassigned @BenediktHensen

**Comment by wekitecs** [comment]
In GitLab by @klamma on Jul 17, 2020, 15:25

I like the idea with using an online service for texttospeech

**Comment by wekitecs** [comment]
In GitLab by @fwild on Jul 17, 2020, 15:29


maybe use RT voice?
https://forum.unity.com/threads/rt-voice-run-time-text-to-speech-solution.340046/

**Comment by wekitecs** [comment]
In GitLab by @klamma on Jul 17, 2020, 15:29

write a wrapper for offline/online solutions

**Comment by wekitecs** [comment]
In GitLab by @BenediktHensen on Sep 5, 2020, 18:20

I created a wrapper that can be used to switch between different text to speech solutions. For now, we have native support for UWP apps.

Here is some more research on possible text to speech APIs/plugins that we could include:

**Native plugins:**

| Solution | Comment | Pricing | Link |
| --- | --- | --- | --- |
| Speech And Text in Unity iOS and Unity Android  | This project has an MIT license and is still updated. It could be worth, giving it a try for the Android and iOS versions. It also supports Speech to text on these two platforms which could also be useful if the MRTK implementation of this feature does not work on non-Windows devices. | Free (Open-Source) | https://github.com/PingAK9/Speech-And-Text-Unity-iOS-Android |

**Cloud-based:**

| Solution | Comment | Pricing | Link |
| --- | --- | --- | --- |
| MaryTTS | We could host an own server that provides text to speech using the open-source MaryTTS server. | costs for hosting a server | https://github.com/marytts/marytts |
| Google Cloud TTS | Provides synthetic voices and WaveNet voices which are more advanced | Basic voices: Four million characters are free per month, after that $4 per one million characters; WaveNet voices: 1 million characters free per month, after that $16 per one million characters | https://cloud.google.com/text-to-speech?hl=en |
| IBM Watson | Documentation about the API itself is sparse, IBM provides an SDK that should be used for .NET applications: https://github.com/watson-developer-cloud/dotnet-standard-sdk | Free: 10,000 characters per month; Standard: $0.02 per thousand characters | https://www.ibm.com/cloud/watson-text-to-speech |
| Amazon Polly | App authorization is more complex. Applications do not send a secret key but a series of hash signatures to communicate with the API; text can be cached in the cloud so that it does not need to be converted again. There is a Nuget package for Amazon Polly that should work with Unity. https://github.com/aws/aws-sdk-net | $4 per 1 million characters for basic voices; $16 per 1 million characters for DeepLearning voices. In the first year, 5 million characters are free per month of the basic voice and 1 million characters per month of the advanced voices | https://aws.amazon.com/polly/?nc=sn&loc=0 |

**Comment by wekitecs** [comment]
In GitLab by @BenediktHensen on Sep 10, 2020, 23:15

removed milestone

**Comment by wekitecs** [comment]
In GitLab by @fwild on Sep 14, 2020, 11:38

Here is an example of how to use Watson: https://github.com/Yu713/daimon

I like Watson - been around for a while and works well. It does cost money (caps the requests, if we run out of quota), the free version takes us only that far. Moreover, the best way to configure it is with a credentials file that is excluded in the gitignore. This way, users of Mirage·XR will have to setup the credentials file themselves, before they are able to use it - may be an idea to catch the auth error in this global routine so we suppress the functionality (rather than breaking the app)?

**Comment by wekitecs** [comment]
In GitLab by @BenediktHensen on Jan 21, 2021, 16:24

unassigned @BenediktHensen

**Comment by wekitecs** [comment]
In GitLab by @wild on Feb 24, 2021, 12:50

Move to Sprint 6? We can look at this together with the Watson integration for Holographic AIs - or the MAAIND toolkit integration.

**Comment by wekitecs** [comment]
In GitLab by @a85jafari on Apr 18, 2021, 15:24

@wild Is this free?!
https://docs.microsoft.com/en-gb/azure/cognitive-services/speech-service/overview

**Comment by wekitecs** [comment]
In GitLab by @wild on Sep 10, 2021, 13:09

We have now added Watson support and can look at the speech input/output in this context.

**Comment by fwild** [comment]
Closing this ticket - solution identified, new ticket should be opened if we consider speech commands to be added for mobile.
