### ISSUE TITLE
Virtual Instructor: Push to talk button design

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#2021]
Currently, the microphone record button is overlaid on top of the menu - ideally this would be a screen space button, placed slightly differently on mobile, iPad, and world space. For example, this push to talk / push again to stop button could be flashmeeting style in the middle of the screen on both mobile and ipad, and slightly in front of the person (within reach) on the world space UI.

**Comment by fominykh** [comment]
@fwild we need to discuss.

**Comment by fominykh** [comment]
![image](https://github.com/user-attachments/assets/2f108534-81d0-4706-a1c9-1dd323246a93)
