### ISSUE TITLE
Virtual Instructor:  check UI

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#2023]
Carefully check the UI as implemented and see if any changes need to be applied.

**Comment by fominykh** [comment]
Check "Design review" page in Mobile UI figma:
![image](https://github.com/user-attachments/assets/5f8d621f-e36a-4fd3-acb6-824a7c153b09)

**Comment by AKissmehl** [comment]
See https://github.com/WEKIT-ECS/MIRAGE-XR/pull/2065
