### ISSUE TITLE
 Error in activity structure in Moodle causing activity steps missing when opening the activity

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#2047]
How to reproduce:
1. Open activity "Suitcase scenario" by use Eirini Christou
2. Observe that there is only one step
3. In developer mode, version 2.7, the app shows an error.
4. When trying to calibrate, the calibration procedure cannot be completed. The app shows an error.
5. When checking the activity in Moodle, there is only one Step, but it includes augmentations that refer to IDs of other steps (which probably existed earlier).

**Comment by fominykh** [comment]
![Screenshot_20240729_212920_MirageXR.jpg](https://github.com/user-attachments/assets/a5ae2887-078f-44b5-bf44-fbdfc6c6c4f5)

![Screenshot_20240729_212910_MirageXR.jpg](https://github.com/user-attachments/assets/bbf6bca9-2d09-4406-86e8-7f83b4ba66c1)

**Comment by fwild** [comment]
resolved, closing.
