### ISSUE TITLE
Update the Speech Settings of the Virtual Instructor based on the design review

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#2051]
The design review has been done in this issue: https://github.com/WEKIT-ECS/MIRAGE-XR/issues/2023
Multiple layout and font issues identified.
@Alvareon can you check how the current UI of the Speech Settings is done? And after that talk to @AKissMail ?

**Comment by Alvareon** [comment]
@fominykh @AKissMail I've updated the settings panel according to the Figma design. I've moved the repeating elements into a separate prefab and updated the layout: PR https://github.com/WEKIT-ECS/MIRAGE-XR/pull/2063


Additionally, the following screens need to be fixed: ContextPrompt, Voice, Models, and Language. Please also check each screen at different resolutions using Simulator mode in Unity."

<img width="453" alt="Screenshot 2024-08-21 at 00 28 24" src="https://github.com/user-attachments/assets/e27a0622-bee0-487d-bd3c-6fc5386442ca"><img width="444" alt="Screenshot 2024-08-21 at 00 21 34" src="https://github.com/user-attachments/assets/05a55889-c65f-4398-942c-ce01492f859b">

**Comment by AKissmehl** [comment]
@fominykh Can we close that one?

**Comment by fominykh** [comment]
@AKissMail I didn't see it in a build, but we can close this one. I will do another review later if needed and will open a new issue for it.
