### ISSUE TITLE
Impossible to log on to 2.7 on mobile

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#2098]
Log out of your account on Android.
Try to log in again.
Observe that nothing happens. No errors. No message that the credentials are wrong.![Screenshot_20241001_165817_MirageXR.jpg](https://github.com/user-attachments/assets/c25844f0-aa60-4354-85df-5cb7ebe01d0c)

**Comment by fwild** [comment]
I think this happens only if you login with your email, but not with your username? In any case, we are not going to fix this anymore, as we are soon switching to the new repository. Therefore closing the ticket.
