### ISSUE TITLE
add avatar URL dialogue to profile settings

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#2168]
Can we add the Profile/Avatar dialogue, so that we can copy & paste a URL to select which avatar we want to use?

**Comment by fominykh** [comment]
![image](https://github.com/user-attachments/assets/fac15ccf-e225-45c0-9641-ed4c5caadd7c)

**Comment by fwild** [comment]
can you paste the subsequent + dialogue? I think if we just directly link through to the + add dialogue with url field, this will do for next week and is simpler!

**Comment by fominykh** [comment]
![image](https://github.com/user-attachments/assets/c7f72c82-06dd-4f4a-81a7-952b556d9abd)

All subsequent screens are in the Add Augmentation -> Virtual Instructor. They are the same as for adding a character into the Profile -> Avatar.
