### ISSUE TITLE
sidebar spacing different for step list

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#2171]
The sidebar on step list has different spacing for the type: the word “Dashboard” runs into the margin

![image](https://github.com/user-attachments/assets/86964d33-8282-4b1c-950e-1bf6f71eca9a)

**Comment by Alvareon** [comment]
@fwild I can't reproduce in the editor, please check it again after the last update of the sidebar

![Image](https://github.com/user-attachments/assets/87d97395-a6df-4043-b75b-048bc2abc9f1)
