### ISSUE TITLE
activity list group title wrong

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#2173]
The activity list has a heading “space activity group” - I think this should be named differently, maybe this was meant to be “Activities”? Or nothing?

**Comment by fominykh** [comment]
The title "Space activity group" is an example title for a group of activities we came up with in the design.
Having this title assumes that we group activities together (by a tag or a course), which is not implemented yet.

![image](https://github.com/user-attachments/assets/5c36bd59-4b90-4bf0-91d4-2a01dacc20b4)

**Comment by fwild** [comment]
ok, we should deactivate the element in the current UI then, but keep it for future reference.
