### ISSUE TITLE
sidebar and layer order

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#2174]
there is still something a tad odd with the sidebar layer order:

https://github.com/user-attachments/assets/50c1877f-62f4-4d15-9c46-e046f7370b31

**Comment by fominykh** [comment]
It looks like the side menu size depends on which menu item is selected. 
![image](https://github.com/user-attachments/assets/4a7c47d1-e7ca-4e9b-9552-06898c8714a2)
![image](https://github.com/user-attachments/assets/e1a0eb5f-c5bc-4103-8d1c-059c12b14c39)
