### ISSUE TITLE
Android CI pipeline

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#235]
In GitLab by @BenediktHensen on Feb 4, 2021, 15:21

Create the CI job that builds the Android installer.

**Comment by wekitecs** [comment]
In GitLab by @BenediktHensen on Apr 22, 2021, 11:08

Currently on hold until the error with the sign tool (#377) is fixed.

**Comment by wekitecs** [comment]
In GitLab by @BenediktHensen on May 6, 2021, 14:59

Might require #402 to be realized first in order to get the updated Gradle version that ships with Unity.

**Comment by wekitecs** [comment]
In GitLab by @a85jafari on Jul 22, 2021, 16:11

Related to #402

**Comment by wekitecs** [comment]
In GitLab by @BenediktHensen on Nov 4, 2021, 15:34

Currently waiting for #658 to get fixed.

**Comment by wekitecs** [comment]
In GitLab by @wild on Nov 9, 2021, 15:36

I think this is fixed (#658)

**Comment by fwild** [comment]
Working, but with a bug in the packagemanager at the moment. closing, as this is a separate ticket.
