### ISSUE TITLE
UI for Kids (Android/iOS)

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#251]
In GitLab by @william.guest on Feb 9, 2021, 09:57

Create a child-friendly interface for mobile platforms.

**Comment by wekitecs** [comment]
In GitLab by @wild on Feb 16, 2021, 17:59

Ideally, we can switch the UI from adult to kid-friendly via the PlatformManager - reading values from a config file for the CI build pipeline? The kiddie friendly version is for the ARETE PBIS use case, but we need to have a grown up version, too.

**Comment by wekitecs** [comment]
In GitLab by @cawke on Feb 17, 2021, 24:36

Do you want the children's version to be a separate app? I thought it would be a separate window with settings where you could choose which interface to display.

**Comment by wekitecs** [comment]
In GitLab by @cawke on Feb 17, 2021, 24:37

and are there more specific requirements as to what the interface should look like for children?

**Comment by wekitecs** [comment]
In GitLab by @wild on Feb 17, 2021, 12:00

I like the idea that you can choose in the configuration panel :)

**Comment by wekitecs** [comment]
In GitLab by @wild on Feb 24, 2021, 12:47

Move to Sprint 6?

**Comment by wekitecs** [comment]
In GitLab by @cawke on Feb 24, 2021, 12:51

I think yes

**Comment by fwild** [comment]
has been implemented by CNR
