### ISSUE TITLE
Provide Templates for Learning Activities

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#274]
In GitLab by @wild on Feb 15, 2021, 11:56

Authors of learning activities need more guidance. We need a mechanism for providing "blueprints" for an AR learning experiences. This of course would require to be able to look through (maybe even search through) the library of existing templates. Each template should guide the author through creating the learning experience, step by step.

For example, there could be a template "Positive Behaviour Intervention Support: Walk Calmly", which advises the author to create three steps. The first step containing some audio instruction what to do and maybe a locate glyph to indicate where the user should stand. The author instructions for this step should tell the author that the locate should be placed at the beginning of a corridor, with several meters of free space in front of the user available. The second step then could advise to create five 3D character models, with the behaviour "walk around" selected. And that the text in the instruction should say something about going to the end of the corridor calmly. Then for the final step, the templating system should guide the author to create a video of how someone runs down the corridor, bumping into everyone. We haven't figured out yet how to pull out the xAPI data about how often the user bumped into a 3D character model, but I'd imagine that the template would instruct the author in how to set that up as well.

I guess we could work off the tutorial code for such templates? 

Related to https://platform.xr4all.eu/wekit-ecs/mirage-xr/-/issues/469

**Comment by wekitecs** [comment]
In GitLab by @wild on Jun 15, 2021, 11:52

We could simply provide a checkbox somewhere that says "[ ] activity template", which then lists them in the system with a boolean flag as template. Might be useful to provide an alternative search for blueprint templates, so that they do not clutter up the usual list of activities.

**Comment by wekitecs** [comment]
In GitLab by @wild on Jun 15, 2021, 11:54

This might require an augmentation "authoring hint" (or "editing hint" or "template instruction") with text / audio, that is only visible in edit-mode and is not displayed to the learners in play-mode.

**Comment by fwild** [comment]
Superseded by other tickets. closing.
