### ISSUE TITLE
Compress audio

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#294]
In GitLab by @wild on Feb 18, 2021, 15:41

As mp3 or something smaller than wave?

**Comment by wekitecs** [comment]
In GitLab by @wild on Feb 18, 2021, 17:42

There seem to be a gazillion LameMp3 converters, but getting something cross platform will be hairy.

**Comment by fwild** [comment]
this could be useful: 
https://github.com/alberto-gglez/Unity-AudioClip-to-mp3
https://github.com/ProGM/Unity3D-save-audioClip-to-MP3/tree/memory-leaks-and-bugs
https://github.com/Superbil/build-lame-for-iOS

**Comment by fwild** [comment]
https://forum.unity.com/threads/exporting-mp3-file-from-audioclip.697175/

**Comment by fwild** [comment]
The audio augmentation now allows upload of MP3s, so this is has now a work around - and client side recompression is not really justified, but - if anything - it should be a server-side service. Closing for now.
