### ISSUE TITLE
'warning' glyph

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#301]
In GitLab by @wild on Feb 24, 2021, 10:54

The resources folder contains under SymbolSprites a copy of all the ISO warning, hazard, and safety instruction signs. We should build an interface for it - a 'warning' glyph for them. The player already can interpret the ARLEM standard for that (please double check that we have not removed the code for that). The standard (p. 12) allows to use the ISO signs in two ways: to use it in an activate or deactivate statement ("type":"warning" and "augmentation":"E007"). If there is a target referenced (e.g. "target":"board1"), then it should display overlaid on the object location. If not, it should be displayed in a fixed viewport location to be always visible.

The ISO 7010 standard differentiates multiple types of signs, but they are all treated the same in ARLEM, no matter whether mandatory sign, prohibition sign, safe condition sign, or fire safety sign:
https://en.wikipedia.org/wiki/ISO_7010

**Comment by wekitecs** [comment]
In GitLab by @wild on Feb 24, 2021, 10:55

We could use a glyph icon like 
![ISO icons](https://www.brady.co.uk/-/media/brady/emea/products/safety-signs/iso7010collection.jpg?la=en-gb&hash=47C4626F7E771F30404A227C9250D5F1EF987B82 "this")

**Comment by wekitecs** [comment]
In GitLab by @wild on Sep 10, 2021, 14:57

dupe of https://platform.xr4all.eu/wekit-ecs/mirage-xr/-/issues/579, therefore closing this one here.

**Comment by fwild** [comment]
superseded by https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1925
