### ISSUE TITLE
ARfoundation: Inform user if tracking is lost

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#411]
In GitLab by @wild on May 12, 2021, 14:31

Spatial mapping on mobiles sometimes looses tracking (esp. on Android), that's unavoidable. Can we catch an event when that happens and inform the user? Is there maybe some remediative action the user can do to help the mapping recover?

**Comment by fwild** [comment]
I believe this is implemented, @cawke ?
