### ISSUE TITLE
Finetune calibration marker

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#429]
In GitLab by @wild on May 21, 2021, 24:12

The distance of the camera to the marker is quite tricky to get right, especially, when the marker is lying flat on a surface, rather than hanging on the wall. But even on the wall, you have to have quite a specific distance, at which point you cannot see the overlay in full anymore - so it kind of seduces the user to go further away again, stopping the calibration. Room for optimisation, as calibration is for me often quite frustratingly long...

**Comment by fwild** [comment]
Is now much more stable. closing.
