### ISSUE TITLE
Calibration alternative: manual placement

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#447]
Instead of using a calibration marker for the whole activity, it should be possible to define in the recorder that task stations can be placed manually. If all task stations are placed manually or are placed via image marker, then the whole activity no longer requires calibration with the calibration marker, and the calibration instructions should be suppressed.

Info whether a task station can be placed manually by the user should be stored with the activity model, for each action step. Moreover, if the activity does not need a calibration marker at all, we could store this in the header ("placement":"manual") alternatives: "marker" and "auto". 

In the player, for each action step that is set to manual placement, the user should be asked to place on the floor a target, possibly also indicating needed boundary box dimensions (spanning all augmentations from the action step).

This could be a ring on the ground hovering across the spatial map - with the task station diamond floating transparently above at line of sight level (= mobile location or chest level on worldspace). What about edit mode? Should placement happen first thing here, too? Or should it be standard placement in front of user with some visual indicator that this task station diamond is "user-placed"?

Providing a greyed-out preview for placement might be useful, which allows the user to see where they would place the content in the room without collisions. 

Options for rescaling the activity size might be an idea in this context (useful if not enough space available!). 

Alternatively, we could maybe also allow setting this globally for all task stations of an activity. In that case, it probably needs calculation of a box model of a boundary box around all augmentations in all the action steps and a single placement only (not placement for each task station again and again).

**Comment by fwild** [comment]
Ring on the ground hovering across the spatial map - with the task station diamond floating transparently above at line of sight level (= mobile location or chest level on worldspace). What about edit mode? Should placement happen first before inspecting? Or random placement in front of user with some visual indicator that it is "user-placed"?

**Comment by fwild** [comment]
This should be the preferred default option - all the other ones (image target, calibration marker) should be 'expert' functionality
