### ISSUE TITLE
Objects are too easily moved by accident when authoring (edit mode only)

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#456]
In GitLab by @william.guest on Jun 2, 2021, 17:46

This is particularly important for large models or situations where you overlay one model onto another (e.g. ribcage and patient).

One possible solution is to add a lock button, the effect which could disable the object manipulator and perhaps change the colliders associated with the object, to prevent losing access to smaller models placed inside larger ones.

**Comment by fwild** [comment]
lock button now implemented.
