### ISSUE TITLE
Add separate config files for different apps

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#467]
In GitLab by @wild on Jun 11, 2021, 12:41

So that we can compile multiple apps with pipeline jobs, by simply copying the config file (or command line switching the config file that shall be used). So: there would be three config files for the moment: mirageXRconfig-ARETE.txt, mirageXRconfig-OpenReal.txt and mirageXRconfig-WEKIT.txt

**Comment by wekitecs** [comment]
In GitLab by @wild on Jun 11, 2021, 12:42

Config file name should probably be added to the BrandManager as well, so that its clear, which config file is used, and manual builds can quickly switch.

**Comment by fwild** [comment]
Done (Assets/MirageXR/Resources/MirageXRConfig.txt) - but could use some script configuration in the pipeline, tbc
