### ISSUE TITLE
Switch off augmentations selectively based on if-rules from xAPI queries

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#473]
In GitLab by @wild on Jun 18, 2021, 15:50

Allow to switch off an augmentation, if e.g. a certain practice level (or proficiency level = outcomes) is reached (level 0: learn, level 1: rehearse, level 3: assess), or if the user entered a specific place (e.g.: show 3D hospital bed when at home, but use real bed when at hospital). This makes activities more adaptive, but in a very automated way.

**Comment by fwild** [comment]
Too complex, closing.
