### ISSUE TITLE
CI pipeline for previews: Merge request details in preview release notification

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#487]
In GitLab by @wild on Jun 29, 2021, 16:36

Would be cool, if we had more info in the slack notification - such as title and description of the merge request that lead to the pipeline preview build. And the branch name?

**Comment by fwild** [comment]
@ManuelPozor - I think you added this now, right?

**Comment by ManuelPozor** [comment]
The last commit message should be displayed, yes.

**Comment by ManuelPozor** [comment]
I did not add other details yet. But the scripts can easily be modified at any point.

**Comment by fwild** [comment]
great! 
-- closing this ticket.
