### ISSUE TITLE
GhostTrack: add finger tracking

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#488]
In GitLab by @wild on Jul 1, 2021, 15:40

MRTk now allows for tracking fingers - we should add this for the ghost (making sure that on mobiles - and HL1? it has a graceful degradation).

**Comment by fwild** [comment]
This is a duplicate of https://github.com/WEKIT-ECS/MIRAGE-XR/issues/871 - therefore closing this ticket.
