### ISSUE TITLE
Refactor unnecessary update methods into event-driven logic

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#494]
In GitLab by @BenediktHensen on Jul 8, 2021, 16:33

Check the code for Update and LateUpdate methods. Some of them just check every frame if a value has changed and then react to that change. If the change only happens occasionally, it is better to transform the part into an observer pattern: The observing class subscribes to an event that is raised if the value changes.
Since these change of the given value is likely not globally relevant but only for the observer, the event should not be integrated into the event manager but can instead be directly part of the observed class.

**Comment by wekitecs** [comment]
In GitLab by @klamma on Mar 3, 2022, 15:36

perhaps move to refactoring II

**Comment by wekitecs** [comment]
In GitLab by @wild on Mar 7, 2022, 12:25

Seems ok - but not sure which classes this particularlry refers to? (= might have been done already as part of the refactoring so far?)

**Comment by fwild** [comment]
@BenediktHensen I think a significant part of this has been done - the core now has proper event driven logic for activities and workplaces. Shall we close this ticket - or add a new one to refactor other parts of the system into an event-driven logic? what?
