### ISSUE TITLE
Investigate how to load content like the avatars dynamically

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#495]
In GitLab by @BenediktHensen on Jul 8, 2021, 16:39

We should not package large content like the avatars completely in the installation file. Instead, it makes sense to distribute them via loadable packages.

The proposed solution here is to have a package manager in the application where you can opt in or out of this additional content, similar to the activity loader. For instance, you can select one or more of the available avatars in this package manager. Then, the selected avatars get downloaded and are saved locally. This way, they will also be available later on in cases that there is no internet. The available options for the augmentations are then automatically adapting to the fact whether an avatar was downloaded or not.

To realize this, we could use an own option, similar to the download and saving of the activities, we could use AssetBundles or we could use [Unity's Addressables](https://docs.unity3d.com/Packages/com.unity.addressables@1.18/manual/index.html) package.

**Comment by wekitecs** [comment]
In GitLab by @a85jafari on Jul 9, 2021, 08:44

Currently the character models will be saved in the zip file. We have their assetbundles in the project folder. We can upload them(assetbundles) somewhere and download them when needed. So we can delete all models and prefabs from project. 
We can do that for glyphs too.

**Comment by wekitecs** [comment]
In GitLab by @a85jafari on Aug 6, 2021, 12:54

unassigned @a85jafari

**Comment by fwild** [comment]
We have now two tickets for this: https://github.com/WEKIT-ECS/MIRAGE-XR/issues/943 and https://github.com/WEKIT-ECS/MIRAGE-XR/issues/947, therefore closing this issue.
