### ISSUE TITLE
Find a way to replace GameObject.Find

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#496]
In GitLab by @a85jafari on Jul 9, 2021, 08:47

Find a way to replace GameObject.Find and transform.FindDeepChild with methods which are not depend to the names.

**Comment by wekitecs** [comment]
In GitLab by @klamma on Mar 3, 2022, 15:35

perhaps move to refactoring II

**Comment by fwild** [comment]
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/ActionDetailView.cs:87:        var activeTSdiamond = GameObject.Find(actionId).transform.Find("default").transform.Find("PlayerTaskStation(Clone)").gameObject; //TODO: possible NRE 
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/AudioEditor.cs:129:            var audioPlayer = GameObject.Find(annotationToEdit.poi).GetComponentInChildren<AudioPlayer>();
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/AudioEditor.cs:166:            audioSource = GameObject.Find(annotation.id).GetComponentInChildren<AudioSource>();
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/AudioEditor.cs:313:                GameObject.Find(annotationToEdit.poi).GetComponentInChildren<AudioPlayer>().DialogRecorderPanel = character.transform.GetChild(0).GetComponentInChildren<DialogRecorder>(); //TODO: Possible NRE
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/AudioEditor.cs:352:            GameObject originT = GameObject.Find(detectable.id);
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/AudioEditor.cs:355:            var annotationStartingPoint = GameObject.Find("AnnotationSpawnPoint");
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/AudioEditor.cs:378:            var player = GameObject.Find(annotationToEdit.poi).GetComponentInChildren<AudioPlayer>();
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/CharacterAugmentation.cs:76:                GameObject originT = GameObject.Find(detectable.id);
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/CharacterAugmentation.cs:94:                character = GameObject.Find(characterObjectName);
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/DrawingEditor.cs:135:                GameObject originT = GameObject.Find(detectable.id);
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/DrawingEditor.cs:193:            GameObject originT = GameObject.Find(detectable.id);
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/DrawingEditor.cs:209:            if (annotationToEdit != null && GameObject.Find(annotationToEdit.poi).GetComponentInChildren<AudioPlayer>() != null)
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/DrawingEditor.cs:211:                GameObject.Find(annotationToEdit.poi).GetComponentInChildren<AudioPlayer>().PlayAudio();
Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/GhosttrackEditor.cs:75:        var originT = GameObject.Find(detectable.id);
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/GhosttrackEditor.cs:198:            Destroy(GameObject.Find("GhostOrigin"));
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/GhosttrackEditor.cs:204:        _augOrigin.rotation = GameObject.Find(_action.id).transform.rotation;
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/GhosttrackEditor.cs:216:            MirageXRLearningHubControl lhControl = GameObject.Find("MirageXRManagers").GetComponent<MirageXRLearningHubControl>();
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/GhosttrackEditor.cs:238:            _augOrigin = GameObject.Find(_action.id).transform;  //TODO: possible NRE. replace with direct ref
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/Glyph/GlyphEditor.cs:68:                GameObject originT = GameObject.Find(detectable.id);
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/ImageEditor.cs:114:            var originT = GameObject.Find(detectable.id);
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/ImageMarker Prefabs/ImageMarkerController.cs:37:            GameObject tracker = GameObject.Find("MixedRealityPlayspace");
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/ImageMarker Prefabs/ImageMarkerController.cs:58:            detectableOB = GameObject.Find(detectable.id);
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/ImageMarker Prefabs/ImageMarkerController.cs:110:            if (!GameObject.Find(ImgMName))
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/ImageMarker Prefabs/ImageMarkerController.cs:204:               GameObject detectableParentObj = GameObject.Find("Detectables");
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/ImageMarker Prefabs/ImageMarkerController.cs:218:            //IM.GetComponent<TrackableEventHandlerEvents>().augmentation = GameObject.Find(detectable.id); ;
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/ImageMarker Prefabs/ImageMarkerController.cs:225:            GameObject augmentation = GameObject.Find(detectable.id);
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/ImageMarker Prefabs/ImageMarkerController.cs:227:            augmentation.transform.parent = GameObject.Find(ImgMName).transform;
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/ImageMarker Prefabs/ImageMarkerController.cs:242:            GameObject detectableObj = GameObject.Find(detectable.id);
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/ImageMarker Prefabs/ImageMarkerController.cs:243:            GameObject detectableParentObj = GameObject.Find("Detectables");
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/ImageMarkerEditor.cs:179:            GameObject originT = GameObject.Find(detectable.id);
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/LabelEditor.cs:64:                GameObject originT = GameObject.Find(detectable.id);
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/ModelEditor.cs:45:                GameObject originT = GameObject.Find(detectable.id);
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/PickAndPlace/PickAndPlaceController.cs:156:            var newModel = GameObject.Find(MyModelID);
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/PickAndPlace/PickAndPlaceController.cs:161:                newModel = GameObject.Find(MyModelID);
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/PickAndPlace/PickAndPlaceEditor.cs:30:            GameObject originT = GameObject.Find(detectable.id);
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/VFX/VFXEditor.cs:65:                GameObject originT = GameObject.Find(detectable.id);
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/VideoEditor.cs:130:            GameObject originT = GameObject.Find(detectable.id);
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionEditor.cs:252:            var newModel = GameObject.Find(pick.MyModelID);
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/ActionEditor.cs:262:        var oldModel = GameObject.Find("ArrowModel_" + pick.GetComponentInParent<PickAndPlaceController>().MyPoi.poi); //TODO: possible NRE
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/PoiEditor.cs:92:        Transform originT = GameObject.Find(detectable.id).transform;
- [ ] Assets/MirageXR/Common/Scripts/CombinedEditor/TaskStationEditor.cs:20:        taskStationMover.HostTransform = GameObject.Find(associatedDetectable.id).transform;
- [ ] Assets/MirageXR/Common/Scripts/GhosttrackPrefabPlayer.cs:35:            _anchor = GameObject.Find(content.id).transform;  //TODO: possible NRE. replace with direct ref
- [ ] Assets/MirageXR/Common/Scripts/Services/ActivityRecorderService.cs:78:            debugText = GameObject.Find("HUD/Text");
- [ ] Assets/MirageXR/Common/Scripts/Services/ActivityRecorderService.cs:358:                    GameObject.Find("RecorderControlPanel/Buttons/SaveArlem/ObjectText").GetComponent<Text>().text = "Save Recording";
- [ ] Assets/MirageXR/Common/Scripts/Services/ActivityRecorderService.cs:363:                    GameObject.Find("RecorderControlPanel/Buttons/SaveArlem/ObjectText").GetComponent<Text>().text = "Error, try again";
- [ ] Assets/MirageXR/Common/Scripts/SetStartingPosition.cs:15:        _userViewport = GameObject.FindGameObjectWithTag("UserViewport").transform;
- [ ] Assets/MirageXR/Common/Scripts/ShowCards/ShowCardsButton.cs:41:            manager = GameObject.Find("UiManager").GetComponent<UiManager>();
- [ ] Assets/MirageXR/Common/Scripts/UnitTestManager.cs:9:        return GameObject.Find(name);
- [ ] Assets/MirageXR/Player/Scripts/ActionListMenu/ActionListMenu.cs:216:                target = GameObject.Find(annotation.poi).GetComponentInChildren<MirageXR.CharacterController>().transform;
- [ ] Assets/MirageXR/Player/Scripts/ActionListMenu/ActionListMenu.cs:219:                target = GameObject.Find(annotation.poi).GetComponentInChildren<PickAndPlaceController>().Target;
- [ ] Assets/MirageXR/Player/Scripts/ActionListMenu/ActionListMenu.cs:222:                target = GameObject.Find(annotation.poi).GetComponentInChildren<GhostRecordPlayer>().transform;
- [ ] Assets/MirageXR/Player/Scripts/ActionListMenu/ActionListMenu.cs:225:                target = GameObject.Find(annotation.poi).transform;
- [ ] Assets/MirageXR/Player/Scripts/Augmentations/Detect/Detect.cs:47:            _startingPoint = GameObject.FindGameObjectWithTag ("MainCamera").transform;
- [ ] Assets/MirageXR/Player/Scripts/Augmentations/ImageViewer/FloatingImageViewer.cs:45:        //    _contentPanel = GameObject.FindGameObjectWithTag("ContentPanel").transform;
- [ ] Assets/MirageXR/Player/Scripts/Augmentations/MirageXRPrefab.cs:91:                _centerOfView = GameObject.FindGameObjectWithTag("MainCamera").transform;
- [ ] Assets/MirageXR/Player/Scripts/Augmentations/MirageXRPrefab.cs:123:            var targetObject = GameObject.Find(obj.id + "/default");
- [ ] Assets/MirageXR/Player/Scripts/Augmentations/MirageXRPrefab.cs:148:            if (GameObject.Find("UiManager").GetComponent<UiManager>().IsFindActive || obj.guide)

**Comment by fwild** [comment]
- [ ] Assets/MirageXR/Player/Scripts/Augmentations/MirageXRPrefab.cs:153:                    //GameObject.Find(obj.id).transform.GetComponentInChildren<PathRoleController>(true).IsVisible = true;
- [ ] Assets/MirageXR/Player/Scripts/Augmentations/MirageXRPrefab.cs:245:                var tempTransform = GameObject.FindGameObjectWithTag("UserViewport").transform;
- [ ] Assets/MirageXR/Player/Scripts/Augmentations/MirageXRPrefab.cs:277:                var temp = GameObject.Find($"{obj.id}/{obj.poi}");
- [ ] Assets/MirageXR/Player/Scripts/Augmentations/Model/Old/MirageXRVideoAnnotationEditor.cs:160:        videoPlayer = GameObject.Find("VideoDisplay").AddComponent<VideoPlayer>();
- [ ] Assets/MirageXR/Player/Scripts/Augmentations/Plugin/PluginEditor.cs:91:                GameObject originT = GameObject.Find(detectable.id);
- [ ] Assets/MirageXR/Player/Scripts/Augmentations/UiSymbol/UiSymbol.cs:37:            transform.SetParent (GameObject.FindGameObjectWithTag ("ActionUi.Symbols").transform);
- [ ] Assets/MirageXR/Player/Scripts/Augmentations/VideoViewer/FloatingVideoViewer.cs:57:            //_contentPanel = GameObject.FindGameObjectWithTag("ContentPanel").transform;
- [ ] Assets/MirageXR/Player/Scripts/Behaviours/DetectableBehaviour.cs:112:            _userPosition = GameObject.FindGameObjectWithTag("MainCamera").transform;
- [ ] Assets/MirageXR/Player/Scripts/Behaviours/HumEnvMqttBehaviour.cs:32:            _humanContainer = GameObject.FindGameObjectWithTag("HumanSensorContainer").GetComponent<RectTransform>();
- [ ] Assets/MirageXR/Player/Scripts/Behaviours/HumEnvMqttBehaviour.cs:33:            _environmentContainer = GameObject.FindGameObjectWithTag("EnvironmentSensorContainer").GetComponent<RectTransform>();
- [ ] Assets/MirageXR/Player/Scripts/Behaviours/PersonBehaviour.cs:71:        //    if (content == null && !GameObject.Find("UiManager").GetComponent<UiManager>().IsFindActive)
- [ ] Assets/MirageXR/Player/Scripts/Behaviours/PlaceBehaviour.cs:73:        //    if (content == null && !GameObject.Find("UiManager").GetComponent<UiManager>().IsFindActive)
- [ ] Assets/MirageXR/Player/Scripts/Behaviours/ThingBehaviour.cs:74:        //    if(content == null && !GameObject.Find("UiManager").GetComponent<UiManager>().IsFindActive)
- [ ] Assets/MirageXR/Player/Scripts/Character Aug/CharacterController.cs:1170:                StartCoroutine(MoveMyImage(GameObject.Find(MyImageAnnotation.poi), MyImageAnnotation));
- [ ] Assets/MirageXR/Player/Scripts/Character Aug/CharacterController.cs:1259:                var annotationSpawnPoint = GameObject.Find("AnnotationSpawnPoint");
- [ ] Assets/MirageXR/Player/Scripts/Character Aug/CharacterController.cs:1265:                GameObject.Find(MyImageAnnotation.poi).transform.position = resetPos;
- [ ] Assets/MirageXR/Player/Scripts/Character Aug/CharacterController.cs:1266:                GameObject.Find(MyImageAnnotation.poi).transform.rotation = resetRot;
- [ ] Assets/MirageXR/Player/Scripts/Character Aug/CharacterController.cs:1267:                GameObject.Find(MyImageAnnotation.poi).transform.localScale = new Vector3(0.5f, 0.5f, 0.5f);
- [ ] Assets/MirageXR/Player/Scripts/Character Aug/CharacterController.cs:1269:                StopCoroutine(MoveMyImage(GameObject.Find(MyImageAnnotation.poi), MyImageAnnotation));
- [ ] Assets/MirageXR/Player/Scripts/Character Aug/CharacterController.cs:1291:            var poi = GameObject.Find(annotation.poi);
- [ ] Assets/MirageXR/Player/Scripts/Character Aug/CharacterController.cs:1306:                if (MyImageAnnotation != null) GameObject.Find(MyImageAnnotation.poi).transform.GetChild(0).gameObject.SetActive(charShowsAnImage); //hide the floating image viewer
- [ ] Assets/MirageXR/Player/Scripts/Character Aug/CharacterController.cs:1366:            var audioPlayer = GameObject.Find(_myObj.poi).GetComponentInChildren<AudioPlayer>();
- [ ] Assets/MirageXR/Player/Scripts/Managers/ActivityManager.cs:819:            foreach (Transform trigger in GameObject.Find("Triggers").transform)
- [ ] Assets/MirageXR/Player/Scripts/Managers/ActivityManager.cs:984:                foreach (Transform trigger in GameObject.Find("Triggers").transform)
- [ ] Assets/MirageXR/Player/Scripts/Managers/GhostRecordPlayer.cs:84:                    audioPlayer = GameObject.Find(audioAnnotation.poi).GetComponentInChildren<AudioPlayer>();
- [ ] Assets/MirageXR/Player/Scripts/Managers/ObjectFactory.cs:344:                var objIfExist = GameObject.Find(obj.poi);
- [ ] Assets/MirageXR/Player/Scripts/Managers/ObjectFactory.cs:470:                        temp = GameObject.Find($"{path}label_{obj.text.Split(' ')[0]}");
- [ ] Assets/MirageXR/Player/Scripts/Managers/ObjectFactory.cs:476:                        temp = GameObject.Find($"{path}{obj.predicate}_{obj.option}");
- [ ] Assets/MirageXR/Player/Scripts/Managers/ObjectFactory.cs:482:                        temp = GameObject.Find($"{path}{obj.predicate}_{id}");
- [ ] Assets/MirageXR/Player/Scripts/Managers/ObjectFactory.cs:487:                        GameObject.Find(path).GetComponentInChildren<ImageMarkerController>().PlatformOnDestroy(); //TODO: possible NRE
- [ ] Assets/MirageXR/Player/Scripts/Managers/ObjectFactory.cs:492:                        temp = GameObject.Find(path + obj.predicate);
- [ ] Assets/MirageXR/Player/Scripts/Managers/ObjectFactory.cs:497:                        temp = GameObject.Find(path + obj.predicate);
- [ ] Assets/MirageXR/Player/Scripts/Managers/ObjectFactory.cs:506:                    temp = GameObject.Find(path + obj.predicate);
- [ ] Assets/MirageXR/Player/Scripts/Managers/SpatialMapManager.cs:39:            spatialMapMeshs = GameObject.Find("Spatial Awareness System").GetComponentsInChildren<MeshCollider>();
- [ ] Assets/MirageXR/Player/Scripts/Managers/SpatialMapManager.cs:41:            //TODO; Find a more efficent way of finding the colliders without using 'GameObject.Find'
- [ ] Assets/MirageXR/Player/Scripts/Managers/UiManager.cs:130:            var userViewport = GameObject.FindGameObjectWithTag("UserViewport").transform;
- [ ] Assets/MirageXR/Player/Scripts/Managers/UiManager.cs:237:            if (!PlatformManager.Instance.WorldSpaceUi || GameObject.Find("CalibrationGuide(Clone)") || GameObject.Find("CalibrationGuide"))
- [ ] Assets/MirageXR/Player/Scripts/Managers/UiManager.cs:365:            var loginButton = GameObject.Find("LoginButton");
- [ ] Assets/MirageXR/Player/Scripts/Managers/WorkplaceManager.cs:126:            _thingContainer = GameObject.Find("Things").transform;
- [ ] Assets/MirageXR/Player/Scripts/Managers/WorkplaceManager.cs:127:            _placeContainer = GameObject.Find("Places").transform;
- [ ] Assets/MirageXR/Player/Scripts/Managers/WorkplaceManager.cs:128:            _personContainer = GameObject.Find("Persons").transform;
- [ ] Assets/MirageXR/Player/Scripts/Managers/WorkplaceManager.cs:129:            _detectableContainer = GameObject.Find("Detectables").transform;
- [ ] Assets/MirageXR/Player/Scripts/Managers/WorkplaceManager.cs:130:            _sensorContainer = GameObject.Find("Sensors").transform;
- [ ] Assets/MirageXR/Player/Scripts/Managers/WorkplaceManager.cs:213:                    if (GameObject.Find(sensor.id))
- [ ] Assets/MirageXR/Player/Scripts/Managers/WorkplaceManager.cs:290:                        if (GameObject.Find(sensor.id))
- [ ] Assets/MirageXR/Player/Scripts/Managers/WorkplaceManager.cs:346:                        if (GameObject.Find(thing.id))
- [ ] Assets/MirageXR/Player/Scripts/Managers/WorkplaceManager.cs:449:                            var sensorPoi = GameObject.Find(thing.id + "/sensor");
- [ ] Assets/MirageXR/Player/Scripts/Managers/WorkplaceManager.cs:460:                                var defaultPoi = GameObject.Find(thing.id + "/default");
- [ ] Assets/MirageXR/Player/Scripts/Managers/WorkplaceManager.cs:501:                        if (GameObject.Find(person.id))
- [ ] Assets/MirageXR/Player/Scripts/Managers/WorkplaceManager.cs:727:                    if (!GameObject.Find(pair.AnchorFrame.name))
- [ ] Assets/MirageXR/Player/Scripts/Managers/WorkplaceManager.cs:764:            var calibrationGuide = GameObject.Find("CalibrationGuide");
- [ ] Assets/MirageXR/Player/Scripts/Managers/WorkplaceManager.cs:791:                    if (!GameObject.Find(pair.AnchorFrame.name))
- [ ] Assets/MirageXR/Player/Scripts/Managers/WorkplaceManager.cs:852:            var calibrationGuide = GameObject.Find("CalibrationGuide");
- [ ] Assets/MirageXR/Player/Scripts/Managers/WorkplaceManager.cs:977:                CreatePoiObject(poi, GameObject.Find(place.id).transform);
- [ ] Assets/MirageXR/Player/Scripts/Managers/WorkplaceManager.cs:995:                Destroy(GameObject.Find(poi.id));
- [ ] Assets/MirageXR/Player/Scripts/Managers/WorkplaceManager.cs:1003:                GameObject detectableObj = GameObject.Find(detectable.id);
- [ ] Assets/MirageXR/Player/Scripts/Managers/WorkplaceManager.cs:1004:                GameObject detectableParentObj = GameObject.Find("Detectables");
- [ ] Assets/MirageXR/Player/Scripts/Managers/WorkplaceManager.cs:1014:            if (GameObject.Find(detectable.id))
- [ ] Assets/MirageXR/Player/Scripts/Managers/WorkplaceManager.cs:1185:            if (GameObject.Find(place.id))
- [ ] Assets/MirageXR/Player/Scripts/Mobile/ContentEditors/CharacterEditorView.cs:45:        var character = GameObject.Find(characterObjectName);   //TODO: possible NRE
- [ ] Assets/MirageXR/Player/Scripts/Mobile/ContentEditors/CharacterEditorView.cs:49:            character = GameObject.Find(characterObjectName);   //TODO: possible NRE
- [ ] Assets/MirageXR/Player/Scripts/Mobile/ContentEditors/GhostEditorView.cs:49:        _anchor = GameObject.Find(_step.id).transform;  //TODO: possible NRE. replace with direct ref

**Comment by fwild** [comment]
- [ ] Assets/MirageXR/Player/Scripts/Mobile/ContentEditors/PopupEditorBase.cs:42:        var originT = GameObject.Find(detectable.id);   // TODO: replace by direct reference to the object
- [ ] Assets/MirageXR/Player/Scripts/Triggers/SmartTrigger.cs:88:                var sensorObject = GameObject.Find ("Sensors/" + sensorId);
- [ ] Assets/MirageXR/Player/Scripts/Triggers/SmartTrigger.cs:285:            GameObject.Find("SystemSounds").SendMessage("PlayIotTrigger", SendMessageOptions.DontRequireReceiver);
- [ ] Assets/MirageXR/Player/Scripts/Tutorial/HololensSteps/StepMoveCreatedLabel.cs:18:            GameObject label = GameObject.Find(manager.CreatedLabel.id + "/" + manager.CreatedLabel.poi);
- [ ] Assets/MirageXR/Player/Scripts/Utilities/SmartRotationController.cs:59:                foreach (Transform obj in GameObject.Find("Sensors").transform)
- [ ] Assets/MirageXR/Player/Scripts/Utilities/Utilities.cs:129:                var parentObject = GameObject.Find(parent);
- [ ] Assets/MirageXR/Search/Scripts/CalibrationMarker.cs:52:            if (_actionList == null || !GameObject.Find(_actionList.name)) return;
- [ ] Assets/MirageXR/Search/Scripts/SetPoints.cs:23:                 targetTransform = GameObject.Find (targetObjectName).transform;
- [ ] Assets/MirageXR/Search/Scripts/UIOrigin.cs:34:        followTarget = GameObject.FindWithTag("MainCamera").transform;
- [ ] Assets/MirageXR/Tiltbrush/Editor/BrushDescriptorEditor.cs:37:      var config = GameObject.Find("/App/Config").GetComponent<Config>();
- [ ] Assets/MirageXR/Tiltbrush/Editor/BrushDescriptorEditor.cs:84:      var configObj = GameObject.Find("/App/Config");
- [ ] Assets/MirageXR/Tiltbrush/Editor/RefreshPanelDimensions.cs:26:    PanelManager pMgr = GameObject.Find("/SketchControls").GetComponent<PanelManager>();
- [ ] Assets/MirageXR/Tiltbrush/Scripts/BillboardPanel.cs:22:    m_BillboardTransform = GameObject.Find("LightsPanel(Clone)").transform;
- [ ] Assets/MirageXR/Tiltbrush/Scripts/DevOptions.cs:72:    var config = GameObject.Find("/App/Config").GetComponent<Config>();

**Comment by fwild** [comment]
To check:
git grep -n GameObject.Find
