### ISSUE TITLE
Document Existing Code

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#503]
In GitLab by @BenediktHensen on Jul 22, 2021, 10:18

We should write documentation for the existing code to make it easier for new developers to join and to maintain a shared understanding of the code base.

This includes both in-code [XML comments](https://docs.microsoft.com/de-de/dotnet/csharp/language-reference/xmldoc/) for **public** methods, plain `//` comments for **private** methods and high-level text descriptions of individual modules in the "Documentation/manual" folder.

Existing documentation can be found here: https://wekit-ecs.pages.xr4all.eu/mirage-xr/

**Comment by wekitecs** [comment]
In GitLab by @a85jafari on Aug 6, 2021, 12:50

@cawke @BenediktHensen @a85jafari @william.guest @robhillman97 @john.murphy2 @BorisJov This ticket is for all developers. Please try to add documentation for your existing code and the codes you will write in the future.

**Comment by wekitecs** [comment]
In GitLab by @BenediktHensen on Mar 3, 2022, 15:27

This should be broken down into individual issues for documenting separate classes/modules. To do this, we need to define units of work that are specific tasks.

There should be an own milestone for this overall goal which then bundles all the separate issues.

**Comment by wekitecs** [comment]
In GitLab by @wild on Mar 7, 2022, 12:27

Good idea - I support this (create a 'documentation' sprint)

**Comment by fwild** [comment]
Ticket needs to be broken down into something actionable. Closing.
