### ISSUE TITLE
[ULE-Issue007] Lack of scale function

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#513]
In GitLab by @s.thanyadit on Jul 31, 2021, 17:11

Users cannot change the scale of 3D objects to grab learners’ attention, this is important for 3D objects such as pictures, labels, and visual effects (VFX).

Suggest solutions: provide handle widgets for scale manipulation

**Comment by wekitecs** [comment]
In GitLab by @a85jafari on Aug 6, 2021, 11:59

Some model can be resized. We need to investigate which augmentations do not have this functionality and add it to them. The scale should be store in ToggleObject.scale

**Comment by fwild** [comment]
This is now implemented in version 2.
