### ISSUE TITLE
[ULE-Issue014] 3D objects are not snapped to surfaces

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#520]
In GitLab by @s.thanyadit on Jul 31, 2021, 17:22

Users cannot judge whether 3D objects are placed on the surface or floating, which can make objects such as waypoints or characters appear unnatural. 

![image](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/4fa2bd40352b4e86efb24f59e14c90ad/image.png)

Suggest solution: snap 3D objects to surface, wall, or floor when nearby.

**Comment by wekitecs** [comment]
In GitLab by @a85jafari on Aug 6, 2021, 11:48

Characters will be snapped when they follow a path but when there is only one node the gravity will be disabled for avoiding falling into the ground. Also this let the user to move the characters freely wherever.
For other models like sketchpad models or glyphs, it is the behavior that we expect because to let the user to move them easily. Not all models should be placed on the ground.
@wild Maybe we should have an option for snapping(rigidbody on/off) in annotation menu?

**Comment by wekitecs** [comment]
In GitLab by @wild on Aug 10, 2021, 15:20

I feel we can improve this for character models - but not sure how exactly. The falling through the ground issue is significant - without a ground plane, we cannot allow gravity to pull the character model down. Will is working on a ground plane algorithm from the Spatial Understanding - maybe this will be the solution in the future?

**Comment by wekitecs** [comment]
In GitLab by @wild on Sep 10, 2021, 16:52

@a85jafari this was now refactored, so that the marker ring around the character is tacked to the floor plane (slightly above), right? Please confirm.

**Comment by fwild** [comment]
duplicate entry.
