### ISSUE TITLE
Sketchfab secret: CI pipeline support

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#551]
In GitLab by @wild on Aug 12, 2021, 15:39

Put the content of the json file into a Gitlab secret variable; add support to the pipeline that as first step, ECHO the variable into the SketchfabClient.json in the correct location (Assets\MirageXR\Common\Resources\Credentials).

**Comment by wekitecs** [comment]
In GitLab by @wild on Aug 12, 2021, 15:39

Alternative: Unity remote?

**Comment by wekitecs** [comment]
In GitLab by @BenediktHensen on Aug 12, 2021, 15:53

The echo would be the immediate solution for the current situation. It requires every developer to locally set up the json file and its content needs to be tracked in Gitlab secrets. If there are updates to it, each developer needs to manually update the file.

More comfortable would be a solution with a key vault where the secrets are stored centrally. We would grant developers and CI pipelines access but since this is a cloud-based solution, we would likely need to pay for the service. Available options e.g. are Azure Key Vault and Amazon Key Management Service. 
With these solutions, we can either compile the secrets into the final application at build time or we can configure the app to look up the credentials during runtime.

Unity Remote Config does this in a similar way and is quite flexible as running app can look up the current config definition online in Unity's cloud service. This means that we can change an app key on the fly and invalidate the old key without breaking the functionality on old releases as they still look up the newest version.

**Comment by fwild** [comment]
superseded by https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1940, closing
