### ISSUE TITLE
Fix the mesh artefacts on character model 'fridolin'

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#564]
In GitLab by @wild on Aug 25, 2021, 21:48

There are still some artefacts - quite possibly Xinyu has fixed these already? But they are not in 1.6.

**Comment by wekitecs** [comment]
In GitLab by @wild on Aug 25, 2021, 21:49

![1.6-fridolin-front](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/29e44ed1d69c271feffefe3ea00d597a/1.6-fridolin-front.jpg)

![1.6-fridolin-back](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/762097b6cf79820ce42112d771c1aa78/1.6-fridolin-back.jpg)

**Comment by fwild** [comment]
Fixed in 1.9, closing.
