### ISSUE TITLE
new 'warnings' augmentation

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#579]
In GitLab by @wild on Sep 2, 2021, 11:49

Add a 'warnings' augmentation with the ISO warnings/hazard signs. The player already supports this (though it might require a renaming to "warnings" to be P1589-2020 standard compliant, and it may not do it 'by the book' - see below) - and the full set of all ISO hazard and warning sign symbols is already in the repo (called SymbolSprites).

Visually, this can look exactly like the vfx and act augmentation: scrollable list of signs.

The standard (p. 12) allows to use the ISO warnings and hazards signs in two ways: to use it in an activate or deactivate statement ("type":"warning" and "augmentation":"E007"). If there is a target referenced (e.g. "target":"board1"), then it should display overlaid on the object location. If not, it should be displayed in a fixed viewport location to be always visible.

The ISO 7010 standard differentiates multiple types of signs, but they are all treated the same in ARLEM, no matter whether mandatory sign, prohibition sign, safe condition sign, or fire safety sign: https://en.wikipedia.org/wiki/ISO_7010

**Comment by wekitecs** [comment]
In GitLab by @a85jafari on Sep 2, 2021, 12:19

@wild I think this is a duplicated issue #301

**Comment by wekitecs** [comment]
In GitLab by @wild on Sep 10, 2021, 14:54

yes. Its a duplicate. I will edit the above and close the old one.

**Comment by fwild** [comment]
superseded by https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1925
