### ISSUE TITLE
bootstrapper: allow to configure specific learning experience and bypass activity manager

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#583]
In GitLab by @wild on Sep 6, 2021, 13:54

this would allow to create single purpose apps and compile them using a bootstrapper config file...

**Comment by fwild** [comment]
I think this is how the QR code should work - open the app, download the activity, start it - but display a bit more waiting screen stuff, so the user does not wander off. And: make sure it actually starts!
