### ISSUE TITLE
V1.6 android crash on open

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#586]
In GitLab by @s.thanyadit on Sep 8, 2021, 13:14

Consistent crash on open on Android 11 (Oxygen OS 11.0.10.10 KB05AA)
One Plus 8T (Snapdragon 856, 12GB Ram)

Initial troubleshooting included
uninstall then reinstall, and restart the phone, clear application cache.
I can also share the log file if you tell me the location.

**Comment by wekitecs** [comment]
In GitLab by @wild on Sep 10, 2021, 14:18

v1.6 (installed over the previous version) works here without crash (Samsung S9, Android 10, up to date with OS updates). This could likely be something system specific. Have you tried to open the app another time after the crash? 

It may be that it is Android 11 - Samsung has not rolled out version 11 yet. Android 10 is api level 29 (released 2019), Android 11 is api level 30 (released 2020). The libraries we use should work from api level 24.

@BenediktHensen @a85jafari @cawke: any idea?

**Comment by wekitecs** [comment]
In GitLab by @a85jafari on Sep 10, 2021, 21:17

I think the best way to find out the issue on a specific device is checking the logcat and see an error that either Android or Unity writes. 
This post can help:
https://answers.unity.com/questions/1543369/how-can-i-debug-my-android-build-when-it-crashes-a.html

**Comment by wekitecs** [comment]
In GitLab by @wild on Sep 13, 2021, 10:19

@s.thanyadit can you please check and see what the logcat shows?

**Comment by wekitecs** [comment]
In GitLab by @a85jafari on Sep 13, 2021, 10:25

@s.thanyadit You can download only Platform tools using the link bellow, if you do not have Android Studio installed on your system.
https://developer.android.com/studio/releases/platform-tools

**Comment by wekitecs** [comment]
In GitLab by @s.thanyadit on Sep 13, 2021, 10:50

Sorry for the late reply,

Please see the attached the logcat [crashlog.txt](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/92288c3ea89046f43aceede3ad7195a7/crashlog.txt)

**Comment by wekitecs** [comment]
In GitLab by @a85jafari on Sep 13, 2021, 11:28

@cawke Could you please check the logcat?

**Comment by wekitecs** [comment]
In GitLab by @wild on Sep 13, 2021, 14:28

These entries in the logcat are funny:

09-13 09:45:52.124 10004 20771 W Unity   : The referenced script (Microsoft.MixedReality.Toolkit.WindowsMixedReality.WindowsMixedRealityCameraSettingsProfile) on this Behaviour is missing!
09-13 09:45:52.124 10004 20771 W Unity   : (Filename:  Line: 199)
09-13 09:45:52.124 10004 20771 W Unity   :
09-13 09:45:52.124 10004 20771 W Unity   : The referenced script (Unknown) on this Behaviour is missing!
09-13 09:45:52.124 10004 20771 W Unity   : (Filename:  Line: 199)
09-13 09:45:52.124 10004 20771 W Unity   :
09-13 09:45:52.124 10004 20771 W Unity   : The referenced script on this Behaviour (Game Object '<null>') is missing!
09-13 09:45:52.124 10004 20771 W Unity   : (Filename:  Line: 334)
09-13 09:45:52.124 10004 20771 W Unity   :

[...]

09-13 09:45:52.134 10004 20771 W Unity   : The referenced script on this Behaviour (Game Object '<null>') is missing!
09-13 09:45:52.134 10004 20771 W Unity   : (Filename:  Line: 334)
09-13 09:45:52.134 10004 20771 W Unity   :
09-13 09:45:52.134 10004 20771 E Unity   : A scripted object (probably Microsoft.MixedReality.Toolkit.WindowsMixedReality.WindowsMixedRealityCameraSettingsProfile?) has a different serialization layout when loading. (Read 80 bytes but expected 92 bytes)
09-13 09:45:52.134 10004 20771 E Unity   : Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?
09-13 09:45:52.134 10004 20771 E Unity   : (Filename:  Line: 2324)

**Comment by wekitecs** [comment]
In GitLab by @cawke on Sep 15, 2021, 14:35

Yes, sure.

**Comment by wekitecs** [comment]
In GitLab by @cawke on Sep 28, 2021, 17:16

@s.thanyadit can you check this build?

https://drive.google.com/file/d/1zW3RXkjch8gIsQtr2LfNJoCL6xpqdG78/view?usp=sharing

**Comment by wekitecs** [comment]
In GitLab by @s.thanyadit on Sep 28, 2021, 17:45

@cawke I checked it and it's still crash on launch after the logo splash screen.
Please find the crash log attached. 

[crashlog.txt](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/a7aa3a4aa1223f4f35e211e507b4ff55/crashlog.txt)

**Comment by wekitecs** [comment]
In GitLab by @cawke on Sep 29, 2021, 01:03

@s.thanyadit thanks. Looks like an error in the native library. 
Can you check another build? I removed vuforia from this build.

https://drive.google.com/file/d/1QnHwofYMEwFPLghbpkEMNtns3YSYbh9o/view?usp=sharing

**Comment by wekitecs** [comment]
In GitLab by @s.thanyadit on Sep 29, 2021, 01:31

@cawke still crash right after grant camera permission, please see the logcat attached. PS. After I see Main camera is missing, I checked permission, the app has access to camera.

[crashlog.txt](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/da266e6195ea170808f54391845584b1/crashlog.txt)

**Comment by wekitecs** [comment]
In GitLab by @a85jafari on Oct 8, 2021, 12:53

@s.thanyadit Could you please test v1.7 on your mobile and check it still crashes?

https://drive.google.com/drive/folders/1VopbW07QnGIuJO3HVhekZxJrI8Y9ZZQs

**Comment by wekitecs** [comment]
In GitLab by @s.thanyadit on Oct 8, 2021, 13:04

still crash on start

Here is the logcat
[crashlog.txt](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/86f3886cab1f4baebe983855959a4f5a/crashlog.txt)

**Comment by wekitecs** [comment]
In GitLab by @wild on Nov 2, 2021, 16:16

We encountered a second Samsung device (using also Android 11) that crashed after the splash screens played. This is the configuration used:

![android-11-crash-Screenshot_20211102-142338_Settings](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/f22481b6002fadde2a55286e1ca24da6/android-11-crash-Screenshot_20211102-142338_Settings.jpg)

**Comment by wekitecs** [comment]
In GitLab by @wild on Nov 2, 2021, 16:16

The device belongs to @smasneri - he is very technically capable and can help bug track :)

**Comment by wekitecs** [comment]
In GitLab by @s.thanyadit on Nov 4, 2021, 15:58

My android version for comparison 
![Screenshot_20211104-145706](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/7500372237ab62bd0e2e68213c58629a/Screenshot_20211104-145706.jpg)

**Comment by wekitecs** [comment]
In GitLab by @wild on Nov 5, 2021, 14:21

This seems to be the documentation:
https://developers.google.com/ar/develop/unity-arf/android-11-build

**Comment by wekitecs** [comment]
In GitLab by @wild on Nov 5, 2021, 14:22

And https://developers.google.com/ar/develop/unity-arf/android-12-build

**Comment by fwild** [comment]
@Santawat last time you said that this is now working. Can you please confirm / close this ticket?

**Comment by Santawat** [comment]
@fwild Yes this is working now, I am closing this issue
