### ISSUE TITLE
Interacting with Aura icons is hard

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#599]
In GitLab by @fominykh on Sep 10, 2021, 17:20

Currently, I have difficulty interacting with the icons on the Aura (e.g., Home icon). When I look down to see the Aura and the icons, the HoloLens 2 stops tracking my hands (even though the hands are still within the fov).
Maybe I simply need a tip on how to do it? 
To reproduce, 
* look straight ahead, raise your hands in front of you
* Hololens can track the hands, raycast works
* Look down to see most of the Aura
* rais your hands in front of your view
* Hololens does not recognize the hands

Device H2, version 1.6 without hotfixes.

**Comment by wekitecs** [comment]
In GitLab by @wild on Sep 13, 2021, 10:25

I generally find interacting with the "home" icon on the aura tricky - as I am quite tall and I have to slouch to be able to track my hands. Something to do with the angle, I suspect. Maybe we should move the "home" icon further up? Maybe someone has a better idea for how we could improve the "home" icon?

**Comment by wekitecs** [comment]
In GitLab by @BenediktHensen on Oct 28, 2021, 16:13

Yes, there seems to be an angle limit at which the HoloLens input does not allow you to point downwards further.

A quick fix might be to increase the size of the aura so that the home icon is not so close in front of you.

Other than that, I would also say that we should move the icons up so that they are something like 20cm above the aura. This way, they are not constantly in the view but we have still improved the pointing angle.
To show that they are part of the aura's UI, there could still be a visible connection between the aura and the icon.

**Comment by fominykh** [comment]
Interacting with the Home button on the Aura is not absolutely impossible. 
The quick fix suggested by @BenediktHensen will not work, I think. Even if we make the Aura double the size, the HoloLens hand rays will not be casted on the floor at all.
![20220928_172822_HoloLens](https://user-images.githubusercontent.com/10297277/192821448-7630df8e-e950-45d9-ae3f-d80ce5e8a714.jpg)

**Comment by fwild** [comment]
Yes, I think we should rahter think about moving all those icons to a hand-palm-based menu?

**Comment by fominykh** [comment]
Yes, let's design it. I think the hand menu can contain:
1. Home menu elements (instead of floating, all Home menu elements, including settings, login etc. can be in the hand)
2. Task list
