### ISSUE TITLE
Delete resume state when locally deleting activity

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#618]
In GitLab by @wild on Sep 21, 2021, 14:34

When you download an activity, then go a few steps in, then exit and locally remove the activity (via trash icon on activity list), and re-download, then the activity is still resuming on the last action step the user saw. This is an uncommon behaviour for the user.

**Comment by fwild** [comment]
can no longer reproduce. closing.
