### ISSUE TITLE
Black solid skies

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#633]
In GitLab by @a85jafari on Oct 8, 2021, 12:50

Currently all scenes have the default hdr sky which will be visible on android build on app start. Change the skies to a solid black.

Connected to:
https://platform.xr4all.eu/wekit-ecs/mirage-xr/-/issues/762 (relocate logos)
https://platform.xr4all.eu/wekit-ecs/mirage-xr/-/issues/764 (swipe through basic concepts at app start)

**Comment by fominykh** [comment]
Done.
