### ISSUE TITLE
Tutorial for Mobile UIs

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#662]
In GitLab by @BorisJov on Oct 28, 2021, 23:28

Similar to the Hololens version, a tutorial should be created for the Mobile UIs. The new TutorialManager should be used for this purpose.

**Comment by fwild** [comment]
* Let's make sure that we have the editor tutorial (and player tutorial) in the new UI! The old UI has it!

**Comment by fwild** [comment]
Any chance we can see the recorder tutorial at least for this Thursday? I have asked Rob to get in touch regarding help with the help view.

**Comment by BorisJov** [comment]
I'm not sure what the recorder tutorial is, so far we've named them Editing and Playing. The editing one will most likely be done until Thursday for the new UI, though some parts need to be added in the code for Alex's new system to work completely. Will keep you updated.
