### ISSUE TITLE
Adding the improved step trigger to audio and video augmentation

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#667]
In GitLab by @a85jafari on Oct 29, 2021, 14:50

Currently we have added the improved step trigger which allows to jump to any steps, to label, act and vfx augmentations. The audio and video still have the old version of step trigger which allows only jumps to the next step. Consider to add the new step trigger to audio and video augmentation as well.

**Comment by fwild** [comment]
adding new ticket for video only, as audio has now the improved step trigger: https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1639
