### ISSUE TITLE
Line from task station to menus not rotating proberly

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#675]
The thin white line from the task station diamond to the augmentation list / task card sometimes goes astray, because it does not rotate properly with the diamond. Investigate and fix.

When you move the task station around the binding line between taskcard and the task station faces the player all the time. But it does not happen for the binding line between the taskstation and the annotation button, therefore the line looks like very weird.

![image](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/a66b5d192716b7d403ff1b8939d213ce/image.png)

**Comment by wekitecs** [comment]
In GitLab by @wild on Nov 15, 2021, 11:46

Also sometimes, the line goes into the far distance.

**Comment by fwild** [comment]
I think we need to redesign the menu anyways for hololens, so I am closing this ticket.
