### ISSUE TITLE
Mobile: augmentation controls for rotate / resize are too fiddly

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#683]
In GitLab by @wild on Nov 2, 2021, 16:02

The bounding boxes for rotation/resizing are in some cases almost impossible to use on a mobile device (e.g., for the character model) - even on a big iPad it can still be tricky. Participants today were struggling a lot with the controls - can't we use some screen space rotation/resize controls alternatively?

**Comment by wekitecs** [comment]
In GitLab by @wild on Nov 9, 2021, 17:44

How about: 
user can tap an augmentation and a slider appears for size - on screen space.

**Comment by wekitecs** [comment]
In GitLab by @wild on Nov 15, 2021, 11:07

Or we increase the boundary box handles?

**Comment by wekitecs** [comment]
In GitLab by @wild on Dec 9, 2021, 16:11

Lock axis constraint and then allow two finger rotate?

**Comment by fwild** [comment]
Has been significantly improved. Therefore closing, and we create a new ticket if we need to do more work.
