### ISSUE TITLE
Mobile: Character model: context panel fiddely to use

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#686]
In GitLab by @wild on Nov 2, 2021, 16:06

The edit panel for the character model (the one to its right) is fiddly to use on mobiles - we need this to be with a screen space menu.

**Comment by fwild** [comment]
Dupe of https://github.com/WEKIT-ECS/MIRAGE-XR/issues/854, closing this one.
