### ISSUE TITLE
Stop image marker tracking if an image marker is stationary to improve stability

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#692]
In GitLab by @robhillman97 on Nov 2, 2021, 17:46

Currently if a marker is tracked the task station will constantly update its position to match the marker. If the marker is stationary than this can cause the task station to jitter about, to stop this the tracking should be stopped if the marker is not moving

**Comment by wekitecs** [comment]
In GitLab by @wild on Nov 4, 2021, 17:18

This may require checking if the position is stable for a couple of frames - so as to avoid making it stationary in the one frame where it is slightly off due to a reflection (or similar).

**Comment by fwild** [comment]
@robhillman97 I believe you did this - the marker is now a lot more stable! Can you confirm and close, please?

**Comment by fwild** [comment]
Test on HL, then close.
