### ISSUE TITLE
Windows store release

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#712]
In GitLab by @wild on Nov 4, 2021, 16:06

Release stable 1.8 to store

Release notes:
https://platform.xr4all.eu/wekit-ecs/mirage-xr/-/issues/707

Privacy policy:
https://platform.xr4all.eu/wekit-ecs/mirage-xr/-/issues/717

**Comment by fwild** [comment]
See also (put two apps into one package): https://github.com/WEKIT-ECS/MIRAGE-XR/issues/711
