### ISSUE TITLE
Better exception handling for crashing augmentation editors

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#723]
In GitLab by @wild on Nov 4, 2021, 17:12

When something breaks, it often breaks more of the functionality - e.g., the + button for adding new action steps stopped working when the ghost recording broke. Maybe we can try/catch this better?

**Comment by fwild** [comment]
I am not quite sure where the instantiation happens in the editor, but one likely place seems to be line 412? ```var newPanel = Instantiate(prefabToLoad);```

**Comment by fwild** [comment]
```
try {
   var newPanel = Instantiate(prefabToLoad);
} catch (Exception e) {
   Debug.Log("Error...");
}
finally
{
   ...
}
```
