### ISSUE TITLE
Plugin does not save the prefab

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#727]
In GitLab by @wild on Nov 9, 2021, 15:06

Please write the prefab of the plugin into the zip file, so it can be downloaded and changed!

At the moment, the workplace model only lists as manifest URL the path to the resource that is shipped with the MirageXR app ("Prefabs/Plugins/CubeNetPlugin/CubeNetPlugin"), but it should be possible that users upload their own prefabs to the Moodle and use it here!

And the easiest way is to use a placeholder plugin that is downloaded and exchanged in the Moodle.

**Comment by fwild** [comment]
@robhillman97 Is this done?
