### ISSUE TITLE
Add all app icons to the BrandConfiguration.cs

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#738]
In GitLab by @wild on Nov 15, 2021, 11:53

We currently seem to set only one main app icon, not all needed for all platforms.
@robhillman97 which icons do we use?

**Comment by wekitecs** [comment]
In GitLab by @robhillman97 on Nov 15, 2021, 13:02

When I set the Icons I set them in the player settings in unity, I haven't added anything to BrandConfiguration.cs as I didn't know we used it for the icons. Currently the default icon is set to "Wekit-logo-v7-300x300":

![DefIcon](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/eb125bc191d58dde3bc544da9d275366/DefIcon.png)

However, for HoloLens builds we also have versions of Wekit-logo-v7 set to the following pixel dimensions; 88x88, 24x24, 142x142, 300x300. Unity says we also need icons of the following sizes for Hololens builds: 

![Icon](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/43a5e4b336de5654d9d861f8520137bd/Icon.png)

Android and IOS seem to only use the set default icon and give no warnings for needing extra variations of the icon

**Comment by fwild** [comment]
does not make things easier - as these would require users (and the action pipelines) to execute the brandconfigurator in editor when building
