### ISSUE TITLE
Collaboration: C5: on-site and off-site

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#748]
Support on-site users with shared AR content and off-site users with shared AR content and a room model (see also 'Digital Twin of Room').

This includes:

- [ ] Refactor the EventManager and events to become compatible with real-time sharing of all editing events (like OnTaskStationMoved). [Here](https://github.com/WEKIT-ECS/MIRAGE-XR/wiki/Events) is the current list of events for both player and editor:
- [] Event Sharing

**Comment by fwild** [comment]
Started documenting them: https://github.com/WEKIT-ECS/MIRAGE-XR/wiki/Events
