### ISSUE TITLE
Collaboration: C2/C3: Create new service for collaboration

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#749]
Wrapper for PhotonEngine, also with base class to allow replacing photon with other, native implementations (e.g. mirror) as fallback.

Foresee functionality for:

- [x]  Session Management: Initiate a collaboration session by inviting team members or sharing join code, so that the participants can securely access the collaborative session.
- [ ] Match making: Allow matchmaking (e.g., 1st 4 into room 1, second 4 into room 2; e.g., pair graphic designer role and voice actor role and astronaut instructor role into one authoring session; e.g. pair learner with instructor into one learning session)

**Comment by fwild** [comment]
btw: there is also an old branch with Orkestra demo code: https://github.com/WEKIT-ECS/MIRAGE-XR/tree/DemoOrkestra - might be worth looking into @robhillman97

**Comment by fwild** [comment]
Matchmaking has priority low, but should of course be foreseen - and implemented if it is easy to do in one go.

**Comment by fwild** [comment]
I am closing this ticket now - we can add matchmaking at a later stage, when we actually need it.
