### ISSUE TITLE
Activities as rooms

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#750]
Activities have a unique ID, which can be used to create an associated "room" - for editing or for viewing. This should be useful when registering master host and the clients. Masters invite or clients request to join - and masters acknowledge. This could all work on the existing activity list UI - just indicating that owner=master is in and clients can now join. Only owner can initiate sharing.

Mind it: edit mode and play mode will ultimately do something very different when sharing (edit mode: master edits, others observe; playmode: users can see different augmentations, like see the same 3D object, but receive different prompts or different task cards).

Users can only be in one channel at a time.

**Comment by fwild** [comment]
Ultimately, we want to be able to book service staff into an authoring session (e.g. "add 15 min with an instructional designer" or "add 15 min with a 3D designer")

**Comment by fwild** [comment]
* Might require shuffling learners in playmode into different rooms (first 4: room 1, second 4: room 2, etc.).
* Editing requires activities to be on the server and be shared, so others can see them in the activity list.
* Editing and viewing most likely require a passcode
