### ISSUE TITLE
Remove list of activities

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#763]
In GitLab by @endrit.kromidha on Dec 7, 2021, 19:34

Remove this list of recordings. Nobody understands what they are and why they are there. The buttons below, the house, three lines etc below don't work either ![Screenshot_20211207-192449_MirageXR](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/23da2786b25108bd4287596524e91f2f/Screenshot_20211207-192449_MirageXR.jpg)

**Comment by wekitecs** [comment]
In GitLab by @wild on Dec 8, 2021, 13:10

@endrit.kromidha This will resolve itself when we switch to the learn.wekit-ecs.com server, so no need to act.

**Comment by wekitecs** [comment]
In GitLab by @wild on Dec 8, 2021, 13:10

made the issue visible to everyone

**Comment by wekitecs** [comment]
In GitLab by @wild on Dec 8, 2021, 13:10

Not quite sure, why the name of the user in line two is box box box. Anyone?

**Comment by wekitecs** [comment]
In GitLab by @klamma on Dec 8, 2021, 13:27

Unicode?

**Comment by wekitecs** [comment]
In GitLab by @cawke on Dec 8, 2021, 18:35

I need to create a new atlas for non-latin characters

**Comment by wekitecs** [comment]
In GitLab by @wild on Dec 8, 2021, 20:27

Yes, as Ralf says - Unicode should handle all that!

**Comment by wekitecs** [comment]
In GitLab by @cawke on Dec 8, 2021, 22:15

https://platform.xr4all.eu/wekit-ecs/mirage-xr/-/issues/768

**Comment by fwild** [comment]
This is redesigned in the new UI 2.0
