### ISSUE TITLE
Things in wrong places

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#765]
In GitLab by @endrit.kromidha on Dec 7, 2021, 19:40

When the app launches for recordings the activities diamond appears not in front of me by almost behind. Not only, they are on my ceiling so I don't know how to reach. The Fridolin character is horizontal in my ceiling. I have not been trained on how to use the left-right controllers remember, and nothing I have not been trained yet should appear yet. You might have to break down and rethink the training steps to real basics. App users from the app store are random people not AR experts. ![Screenshot_20211207-192621_MirageXR](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/fa15d951cc16dfe70411347690646f36/Screenshot_20211207-192621_MirageXR.jpg)

**Comment by wekitecs** [comment]
In GitLab by @wild on Dec 8, 2021, 13:00

@endrit.kromidha You need to calibrate - then everything works as expected.

**Comment by wekitecs** [comment]
In GitLab by @wild on Dec 8, 2021, 13:06

We have already two tickets open that tried to opt out of the calibration:
https://platform.xr4all.eu/wekit-ecs/mirage-xr/-/issues/447 and https://platform.xr4all.eu/wekit-ecs/mirage-xr/-/issues/448

**Comment by wekitecs** [comment]
In GitLab by @wild on Dec 8, 2021, 13:06

made the issue visible to everyone

**Comment by fwild** [comment]
Btw: I believe this direct issue is now gone in release 1.9, right?
