### ISSUE TITLE
Activity list does not display title of the activity - and does not search for title

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#776]
In GitLab by @wild on Dec 17, 2021, 14:56

Since the back-end was changed and the filename is now no longer identical with the activity name, the activity list can no longer search for activity titles. This is very confusing to the user - and we get a lot of requests that their activities no longer exist (though you can open them from Moodle using the play button).

**Comment by wekitecs** [comment]
In GitLab by @a85jafari on Dec 18, 2021, 19:47

I think this issue is only on mobile! In editor the activity title can be searched for

![image](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/ae21f145b43e186e0ef7a1e448cef19b/image.png)

**Comment by wekitecs** [comment]
In GitLab by @cawke on Dec 19, 2021, 07:52

@wild @a85jafari Not sure if this is a problem with the mobile interface. The json comes from the server with an empty title. So the file name is displayed instead of the name until we download the record.

![image](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/b82d4ce9c65658738a79211f48a13935/image.png)
![image](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/b5877a6939fb9d517b150942dbde48cd/image.png)
![image](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/208aec5bb16f9cfbf883fce1477fdcf9/image.png)

**Comment by wekitecs** [comment]
In GitLab by @a85jafari on Dec 19, 2021, 14:43

@cawke @wild I'm not sure by which version and when had you created and uploaded the activity which has not been saved the title. I created an activity on mobile (hello test mobile) with version 1.8 and as you see the title is saved on database. The activity that @cawke tested has no title on database as you can see (id 569), and it is weird! MirageXR will use the filename if the title be empty which is an expected behavior. So can you please test it by creating a new activity using v1.8 or the latest dev branch in editor. By the way, if you open the edit page (on Moodle) of the activities which have no title, and save them(Even without any changes) The title will be saved on database and next time they can be included on Mirage Search result.

![image](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/43aa4daedbfd6cdc6129f5dd8b085455/image.png)

**Comment by wekitecs** [comment]
In GitLab by @wild on Jan 19, 2022, 17:34

there is definitely still something odd going on - I had today the issue of not being able to find a freshly created activity on hololens. Not even after logging out and logging in again - which in the past would freshly fetch the list. I have opened a new ticket - but they may be related?

**Comment by fwild** [comment]
No longer the case (RC 1.9, 2.6.22). closing.
