### ISSUE TITLE
Red arrow assisting in finding an augmentation points to the task station diamond instead

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#782]
In GitLab by @fominykh on Dec 25, 2021, 20:54

To reproduce the bug:
1. Create a new activity, use the first step
2. Create an image, move the image far from the diamond.
3. Open the contents of the step and click the "locate the augmentation" button
4. The red arrow appears, but points to the task station diamond, not to the image (screenshots)
6. Create a text label in the same step.
7. Click "locate the augmentation" button on the label -> the red arrow correctly points to the label.

![Screenshot_20211225-224825_MirageXR](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/2a389cec786b6c91d1db9bcd8dc6647a/Screenshot_20211225-224825_MirageXR.jpg)

![Screenshot_20211225-224819_MirageXR](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/c3828205fe560fdc187e61c45231eb64/Screenshot_20211225-224819_MirageXR.jpg)

**Comment by fwild** [comment]
Still exists in version 2.
