### ISSUE TITLE
More lighting option in the scenes

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#783]
In GitLab by @s.thanyadit on Jan 13, 2022, 12:45

Similar to issues #642.
Added 3D models are often dark. May be allow users to place other types of lighting, such as point light and spot light, in the scene. 

![20211225_040613_HoloLens](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/9d01d64352331df5df4f90a491740e63/20211225_040613_HoloLens.jpg)

**Comment by wekitecs** [comment]
In GitLab by @wild on Jan 13, 2022, 15:43

Fully support this: on Hololens, the light source seems to be somewhere away from the user, instead of from the user? So all 3D models are lit from behind, and the front is dark?

**Comment by wekitecs** [comment]
In GitLab by @s.thanyadit on Mar 23, 2022, 17:51

marked this issue as related to #845

**Comment by fwild** [comment]
duplicate of https://github.com/WEKIT-ECS/MIRAGE-XR/issues/845, closing.
