### ISSUE TITLE
Mobile: Adding Joystick for dedicated control of 3D objects manipulation

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#784]
In GitLab by @s.thanyadit on Jan 13, 2022, 15:56

Similar to #688 and #689.
 
Something like this one
https://assetstore.unity.com/packages/essentials/starter-assets-first-person-character-controller-196525

**Comment by fwild** [comment]
A user pointed me to this, cause they quite liked the controls: https://youtu.be/DraVDdkPvP4?t=167

**Comment by fwild** [comment]
Superseded by proposals for axis lock and moving in one direction only.
