### ISSUE TITLE
Create a new UI for the mobile apps

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#787]
In GitLab by @fominykh on Jan 13, 2022, 16:13

Create a new mobile UI and flow, both visual and logical.

**Comment by wekitecs** [comment]
In GitLab by @fominykh on Jan 13, 2022, 16:13

changed due date to January 13, 2022

**Comment by wekitecs** [comment]
In GitLab by @fominykh on Jan 13, 2022, 16:14

I am inviting @cawke and @fwild to review the new mobile UI.

**Comment by wekitecs** [comment]
In GitLab by @wild on Jan 14, 2022, 15:04


Feedback:

- I don't think "project" is the right terminology. I think "experience" is best ("add new experience", "Cats experience"). "Activity" is what we use in the standard - which is also not quite bad, but "experience" is better. "Project" is only from the author perspective - for users, it is not a "project", but an "experience", which can be quite passive or quite active doing something.

- I can imagine that "step" / "action step" is not the right word: it is confusing to the user that the task station (symbolised by the diamond) and action step are the same thing. But I cannot find anything else that is not equally confusing: "step anchor", "keystone", "anchor", "keyframe", "frame", "focus point". Let's leave it at "step" - that's the least confusing.

- "..." menu: I somehow think that the upload to the cloud should be managed automatically and in the background - leaving it up to availability of the internet connection to sort out when it is uploaded from the local device to the cloud. Same with the 'save to device' - this should happen in the background and automatically.

- View Step: "Content" vs "Info" -> I appreciate "Info", but its a bit ambigious. In the past we used "Instruction" - and that's also what it is called in the standard. I think that's better? And "content" should be "augmentations". I think that's better - though I get that its more difficult to learn; but it is less easy to mix this up with anything else (Info is also a content, isn't it ;).

- Add New content: "Add new content": "Add augmentation"?

- Add new image: "Select content type" -> "Select type"?

- Calibration: I like the global calibration - that's much better and will work towards the "experience stream" idea.

For the user:

- I am not sure that the middle button in the airbar is needed (the "dot in ring" button for current step). I would usually expect that tapping the list icon again makes the list disappear? 

- Access to calibration (for "recalibration" when tracking gets lost) is needed also within each experience

- I would prefer that the "experiences" have a preview window that renders the first action step in the users environment already in the preview, with the "preview window" being a sort of "view finder" looking into each of the augmented realities offered in the list. There should then be a full screen button, which opens the full UI

**Comment by wekitecs** [comment]
In GitLab by @cawke on Jan 20, 2022, 14:30

the input window in unity will be duplicated

![image](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/ce3b9b1540bf76231b4d54d902141cd9/image.png)

**Comment by wekitecs** [comment]
In GitLab by @cawke on Jan 20, 2022, 14:35

I think the forward and backward arrows should be
as we have to go through the step by step

![image](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/a3622b6c0922c600b493447a6124487b/image.png)

**Comment by wekitecs** [comment]
In GitLab by @cawke on Jan 20, 2022, 14:38

about the blur effect. i think it's quite a heavy effect for a mobile platform. we need to do a little research to be sure.
Most likely we will have to write a custom shader and render the entire interface into a separate texture.

![image](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/abbdd7f2cd37f622c744af5ded3d253c/image.png)

**Comment by wekitecs** [comment]
In GitLab by @cawke on Jan 20, 2022, 14:43

This doesn't apply to the new interface, but I'll write here anyway. We do not have the ability to select photos from the gallery.

in the future we will need to add

![image](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/cc39fc16c59b671b1b4f304b422f7e53/image.png)

**Comment by wekitecs** [comment]
In GitLab by @fominykh on Jan 24, 2022, 14:23

Here, the idea is that the user can swipe (scroll horizontally) the rectangle steps. This can be done in the mobile version of the UI. Can it? On HoloLens, buttons are better.

**Comment by wekitecs** [comment]
In GitLab by @s.thanyadit on Feb 11, 2022, 16:46

![Picture1](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/160046169647c3a0fc67253c0aea735f/Picture1.png) 
- Need a scroll bar. Even though the user can use a handscroll to navigate, the scroll bar indicates how long is the list and where is the current position in the list.
- Need a “sorting option” button. Every list needs to indicate how it’s sorted to indicate whether it’s sorted by “dated added”, “date modified”, and “Name”. 
- In the “sorting option”, we can add an option to adjust thumbnail size.
- In my opinion, we should remove the space around the menu to utilize more of the screen space, since the see-through effect is already provided “augmented reality” aesthetic. 
- In each course entry, might need an option icon (“…”) to un-enrolled the course.
- Aesthetic option, the “+” button position can be integrated into the menu bar. Thus, there are no overlapping UI elements. This option avoids overfilling the right side once the scroll bar is added.  
- If the calibration is only needed after the activity is selected, we should remove the calibration button during activity selection and since it’s not used often calibration should be removed from the menu bar but keep it in the “activity” specific menu to re-calibrate.

**Comment by wekitecs** [comment]
In GitLab by @s.thanyadit on Feb 11, 2022, 16:46

![Picture2](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/92d68348820fe6797122a4fcdabb1053/Picture2.png)

This screen should show only the current user profile info and log-out option which go back to the “Enter” screen.

**Comment by wekitecs** [comment]
In GitLab by @s.thanyadit on Feb 11, 2022, 16:47

![Picture3](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/852e70b6716b7adf1bcaaabfe1fb4cae/Picture3.png)

-	This left screen after the user press the “+” button, can be removed entirely and go directly to the right screen with name input and keyboard.
-	On multiple screens, the back arrow has the same functionality as the home button. In those screens, the back arrow should be removed.

**Comment by wekitecs** [comment]
In GitLab by @s.thanyadit on Feb 11, 2022, 16:47

![Picture4](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/50dec86de1e3157e964c3fe42f5b8e00/Picture4.png)

-	Similarly, should add a horizontal scroll bar here.
-	The back arrow here has the same functionality as the home button, the back arrow should be removed.
-	This screen is tricky since the user is supposed to view the 3D augmentations in this screen but 2DUIs are already occupied a quarter of the screen. May need to add an option to further hide 2DUI elements.

**Comment by wekitecs** [comment]
In GitLab by @s.thanyadit on Feb 11, 2022, 16:48

![image](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/36eb0bb40ed8139beb85f33252673182/image.png)

-	This expanded screen provided the same information as the compact screen, the only added functionality is access to the “Info” button. We can either directly show info when the user press on the expand button or add more details in each step (such as a total number of augmentations in each step).
-	Checkboxes are an easier option than long-press for selecting multiple steps, unless the UIs have no space, then the long press is a better option.

**Comment by wekitecs** [comment]
In GitLab by @s.thanyadit on Feb 11, 2022, 16:49

![Picture6](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/5cab16b48516a2e32223b0cd127c9b85/Picture6.png)

-	The “+” button for adding new augmentations should not look the same as the “+” button that adds new activity. Maybe use the same UI theme as other augmentations entries (grey box, with the white letter).
-	Add left and right buttons to navigate to other steps, since hand swipe might not be obvious on this screen. 
-	Contextual buttons, such as locate and delete, can be replaced with icons. The rename button can be removed by allowing the user to press the augmentations name to rename. 
-	At 21/22 the grey frame should be removed from this screen since it is no longer a button, a similar issue with other screens.

**Comment by wekitecs** [comment]
In GitLab by @s.thanyadit on Feb 11, 2022, 16:49

![Picture7](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/be9c1f07036221e0e194643f4a53a0c9/Picture7.png)

-	These screens need a back button to go back to the previous screen.

**Comment by wekitecs** [comment]
In GitLab by @s.thanyadit on Feb 11, 2022, 16:50

![Picture8](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/ce000ea40c42118e79d98a94bcb68e84/Picture8.png)

- The delete screen should include the name of the augmentation to prevent the mistake.
- Pop up dialogue should remove the “x” button since the cancel button accomplishes the same thing.

**Comment by wekitecs** [comment]
In GitLab by @s.thanyadit on Feb 11, 2022, 16:52

![Picture9](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/9a9b820727a8d76c73aa348404dd9380/Picture9.png)

Might move the option to re-calibrate here.

**Comment by wekitecs** [comment]
In GitLab by @wild on Feb 11, 2022, 17:07

Good stuff, thank you @s.thanyadit :)

**Comment by wekitecs** [comment]
In GitLab by @fominykh on Feb 13, 2022, 16:54

All comments look logical to me, @s.thanyadit . I Will review them with the designer, and report at the next dev meeting.

**Comment by wekitecs** [comment]
In GitLab by @fominykh on Feb 13, 2022, 16:55

changed due date to March 01, 2022

**Comment by Alvareon** [comment]
The new screens already created. We've broken this task into smaller tasks for convenience (see Version 2.0). We can close the task.
