### ISSUE TITLE
Plugin: store the prefab in the ARLEM zip

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#788]
In GitLab by @wild on Jan 14, 2022, 11:17

The prefab is currently not stored and online the path to the prefab shipped with the build is included. This should be changed, so that the prefab is included (and then can be replaced by the user via the web interface).

Dupes: https://github.com/WEKIT-ECS/MIRAGE-XR/issues/727 and https://github.com/WEKIT-ECS/MIRAGE-XR/issues/591

**Comment by wekitecs** [comment]
In GitLab by @wild on Jan 28, 2022, 11:26

@robhillman97 Any update? Marielle needs this so she can include WP5 specific developments...

**Comment by wekitecs** [comment]
In GitLab by @robhillman97 on Jan 28, 2022, 11:33

I haven't started on this yet, apologies I didn't realise it was a time sensitive issue. Just to clarify the issue is based around moving the storage of a plugin out of the resources folder and into an activities zip folder similar to how we store images and videos?

**Comment by wekitecs** [comment]
In GitLab by @wild on Jan 28, 2022, 12:30

In the future, the plugin would be in two places: where ever it is now (so it can be included in a new ARLEM - how else would it get into the archive?), but once it is assigned to an ARLEM, the asset prefab should be included in the zip file (so it can be replaced with a different one!).

**Comment by fwild** [comment]
@robhillman97 is this done?
