### ISSUE TITLE
Character Model detached from the ring after walking path

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#798]
In GitLab by @s.thanyadit on Jan 26, 2022, 18:46

Character model detached from the ring after clone and create a walking path, seem like there are issues with the character collision.
Please see video for details.

![MirageXR_2](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/d753a05ece310d580dab9d34c83b2df8/MirageXR_2.mp4)

**Comment by wekitecs** [comment]
In GitLab by @a85jafari on Jan 27, 2022, 11:45

Character model uses navmesh to follow the path, therefore it collide with the colliders which is under the characters.
For finding out what happened here, I need you to record a video from before the character stucks to the roof.(Before cloning the path)

**Comment by wekitecs** [comment]
In GitLab by @wild on Jan 27, 2022, 15:17

Happens to me only, if the mesh path has obstacles - e.g. if the last location is on a table, or if someone walks through the scene. Mind it: if your ring is too close to a wall, the wall may also count as 'obstacle'.

**Comment by fwild** [comment]
I think this ticket needs to be rephrased - this probably more about indicating whether a ring is in a good position, so the author knows whether the expect trouble. I am closing this ticket now, but maybe you want to add a new one, @Santawat?
