### ISSUE TITLE
Calibration marker is orientation sensitive

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#809]
I believe there is also a bug: calibration is sensitive to the orientation of the marker? It should not be - it should not matter whether a marker is lying on the table or hangs on the wall. The world origin should always be the centre of the marker and orientation should always be e.g. up in world space?

**Comment by fwild** [comment]
I am no longer convinced that this is really possible? How would orientation be preserved anyways? Other voices?
