### ISSUE TITLE
Create short animations for the onboarding slides

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#813]
In GitLab by @fominykh on Feb 13, 2022, 17:00

Five (2-seconds) animations, similar to GIF stickers, for the onboarding slides:
1. Human greeting - ghost greeting
2. Ghost in action
3. ”Step-by-step training: Diamond for action step 1 and 2” and “Aura”
4. Guest account -> safe/organizational login
5. Tutorials

**Comment by wekitecs** [comment]
In GitLab by @fominykh on Feb 13, 2022, 17:00

changed due date to March 01, 2022

**Comment by fwild** [comment]
@fominykh any news? do we have them?

**Comment by fominykh** [comment]
Update: needed to update them, could not work with the original designer. A new designed in on the task now.

**Comment by fominykh** [comment]
shared preliminary animations in Slack
