### ISSUE TITLE
Add in app registration for the Moodle

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#815]
In GitLab by @wild on Feb 17, 2022, 10:57

Add in-app registration routines so that the signup (%MOODLEURL%/login/signup.php?) can be executed directly from within the app - parse result and display a screen "Account added. Now check our email and validate it." plus button to return to log in.

We need this for the new UI

**Comment by fwild** [comment]
Moodle does not provide an API for that, so let's not implement this for now, but simply link to the web signup page.
