### ISSUE TITLE
Marker augmentation: display "find this" + marker image

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#816]
In Play Mode: When the marker augmentation is not yet identified (tracking not yet found, position of the task station not yet set to new world anchor, subsequent tracking stopped?), there should be a screen-space dialogue that instructs the user to find the marker, also displaying the marker. 

In this context: user reports: "The image marker would be more useful if there was an option to display the
educational scenario only when the specific marker would be spotted."

UPDATE: when this functionality moves into the task station, it still makes sense - and it is already foreseen in the new UI!

**Comment by fwild** [comment]
Semi transparent, in a frame, floating in front of the user

**Comment by fwild** [comment]
@robhillman97 are you working on this? Seems to be the last ticket unresolved...?

**Comment by robhillman97** [comment]
I've been working on this today and have two solutions I wanted to float. 

the first is as described, a floating transparent image which is displayed until the marker is tracked

![ImageMarkerPreview1](https://user-images.githubusercontent.com/65968011/207627256-2e88b51d-7dd7-420b-82d4-7e6f964ede66.png)

Would still need a bit of smarting up but the main issue I have with this method is its a bit intrusive and could get in the way especially if the user wants to look away from the marker for any reason. 

The second method I propose is to have a button on the action step in the action step list which only appears if the step has a marker:

![ImageMarkerPreview2btn](https://user-images.githubusercontent.com/65968011/207627800-070420b4-5aab-4239-bca6-4ecc31408bc3.png)

Once clicked it opens a popup which displays the image:

![ImageMarkerPreview2popup](https://user-images.githubusercontent.com/65968011/207627921-a2d02775-6955-4652-9723-48cdc2ccb6ec.png)

@fwild  what do you think?

**Comment by fwild** [comment]
I like option 2 a lot more - could we open the dialogue automatically, and use the button to bring it up again, if the user accidentally clicks it away?

**Comment by fwild** [comment]
Still: if we use option one when the navigation is folded down, add the purple border, and when tapping on it, bring up the "got it" dialogue, then it would be much more clear, even if the user has the menu minimized. I think in this case, the image can be thumbnail size - as a tap on it should fold the menu up and open the purple "got it" dialogue.

**Comment by fwild** [comment]
actually: I can imagine also instead of hiding it somewhere on top that we put a frame around it (the four coner one in turquoise - see what we currently use on the "calibration" tab), and put it in the middle of the screen.

Blocking the view for the user is ok here, as the augmentation cannot work without being tied to the marker! Still needs to be somewhat transparent so the user can properly aim? But not too transparent to allow the user to work without image target?
