### ISSUE TITLE
MirageXR is breaking a connection between a headset and a PC

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#831]
In GitLab by @fominykh on Feb 22, 2022, 17:25

How to reproduce:
1. Connect a wireless headset to both a PC and to an Android phone via Bluetooth
2. Play sound on PC (e.g., start a Zoom meeting) - the sound plays in the headset
3. Start MirageXR app on the phone (that is connected to the same headset)
4. After a few seconds, notice a notification in the headset "call ended", notice that all sounds from the PC to the headset is blocked.
5. The only way to restore the headset - PC connection is to close MirageXR app on the phone.

**Comment by wekitecs** [comment]
In GitLab by @wild on Feb 23, 2022, 13:34

I think this is a bluetooth issue of your headset? don't other apps on your phone do the same - like skype, when calling? MirageXR opens the mic on app start, for voice commands. Maybe this is something we should optimise (as on android, voice commands don't work).

**Comment by wekitecs** [comment]
In GitLab by @fominykh on Feb 23, 2022, 17:03

The only other phone app that does a similar interruption is the calling app. However, if I drop/cancel the call, the headset is being released, and I can continue using it connected to the PC.
MirageXR does not have audio device settings. Adding it might be a solution.

**Comment by fwild** [comment]
Outside of our control - still persists, even when using Zoom app or Teams (with Remote Assist plan). Closing.
