### ISSUE TITLE
Add new animations

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#852]
In GitLab by @hxy000713 on Mar 16, 2022, 17:13

We can add more hand gestures and body animations, such as handwriting, sitting, jumping, looking around, etc.![body1]

I find some good references from Google: https://www.google.com/search?q=body+gesture&tbm=isch&ved=2ahUKEwjIvIShpsn2AhWCi_0HHfF1DU0Q2-cCegQIABAA&oq=body&gs_lcp=CgNpbWcQARgAMgQIABBDMgQIABBDMgQIABBDMgcIABCxAxBDMgQIABBDMgQIABBDMgQIABBDMgQIABBDMgQIABBDMgQIABBDOgcIIxDvAxAnOgUIABCABDoGCAAQBxAeOgYIABAFEB46CAgAEIAEELEDUO0PWLkWYKYmaABwAHgAgAFHiAG2ApIBATWYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=FSUxYojeNYKX9u8P8eu16AQ.

 ![hand](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/72a64e50887eacc2991f4137614039f7/hand.png)

![body2](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/1acfe2018825309349aa729135a0478d/body2.jpg)

![body1](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/d12caec3c42a484b526cbb400d2bf027/body1.jpg)

**Comment by fwild** [comment]
Superseded by PhD thesis of Xinyu - with updated animations to come.
