### ISSUE TITLE
Hide the “Accept” button before recording or taking a photo for ghost, audio, and image augmentations.

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#861]
In GitLab by @s.thanyadit on Mar 23, 2022, 18:05

Multiple participants chose the “Accept” button before performing the recording during the evaluation.

Sol: hide the “Accept” button before recording or taking a photo for ghost, audio, and image augmentations. Similarly, the play button should be hidden when there is no audio record to play.

![Picture6](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/ce27964bca4ce9bb0659d4e82ad7dbb0/Picture6.jpg)

**Comment by fwild** [comment]
Already reflected in the new editor panel designs, which are slowly introduced. Closing.
