### ISSUE TITLE
Allow some existing augmentations that have text such as label to be edited after creation.

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#864]
In GitLab by @s.thanyadit on Mar 23, 2022, 18:08

Participants have to create new augmentations from the beginning even though they want to edit the text.

**Comment by wekitecs** [comment]
In GitLab by @wild on Mar 24, 2022, 15:16

Needs to be more specific - which things? Most augmentations are editable at the moment, but I am sure you mean some of these to be more comfortable?

**Comment by wekitecs** [comment]
In GitLab by @s.thanyadit on Mar 24, 2022, 15:57

Updated the description to be more specific. I found these issues mostly in augmentation that has text: label, (maybe) pick and place.

**Comment by fwild** [comment]
I retested on iPad 1.9 release and HL2 1.9 release: this is resolved.
