### ISSUE TITLE
Improve the appearance of the ghost

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#867]
In GitLab by @s.thanyadit on Mar 23, 2022, 18:14

Participants commented that the ghost recording was disturbing.

We should improve the appearance of the ghost. Some participants suggest to use the 3D character model instead of the ghost model. also link to #841

**Comment by fwild** [comment]
The ghost and its design is a unique feature, but we could allow additionally to configure a personalised avatar. Moreover, there is indeed no need to keep ghost and character model separated, if the character models would be enhanced (e.g., they would require some more natural physics system that makes feet follow the head position less rigidly).

**Comment by fwild** [comment]
We have already a readyplayer.me ticket now, I am therefore creating a new ticket about merging ghost / character model, and then will close this one.
