### ISSUE TITLE
Add an in-app short tutorial to demonstrate the feature.

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#868]
In GitLab by @s.thanyadit on Mar 23, 2022, 18:14

Participants rarely read the tutorial text. This issue might be because the tutorial text is too long or the tutorial text is outside of the participants’ view. Video or animated-gif?

If it is done as video, then it should be streaming a YouTube video rather than blowing up the file size.

See also:
https://platform.xr4all.eu/wekit-ecs/mirage-xr/-/issues/761

**Comment by fwild** [comment]
I think the new in app help texts of the redesign are covering this ticket. To be reviewed, when the help texts and updated tutorial is done. Leaving it open for now (but I don't think we need to do this as suggested anymore - the redesign is dealing with this, but in a different way).
