### ISSUE TITLE
Ghost: Record fingers movement

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#871]
Users expect that the ghost recording will also record their finger movements (Santawat). 

MRTk supports finger tracking - as the ghost hands already indicate. Make sure that there is graceful degradation to mobiles, as they cannot record hand and finger movement.

**Comment by fwild** [comment]
This requires to extend the [data frame ](../blob/master/Assets/MirageXR/Common/Scripts/DataModel/GhostDataFrame.cs) so that it holds finger data not only hand pose data.

**Comment by fwild** [comment]
At this opportunity it might be an idea to convert to JSON (and abandon XML). This is a breaking change, so we should make sure there is graceful degradation if fingers are not supported. Or a check for versions is implemented here, so we can still run old files!

**Comment by fwild** [comment]
This has been raised repeatedly now in presentations I gave as questions from the audience!

**Comment by fwild** [comment]
Here is the documentation for the hand tracking: https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk2/features/input/hand-tracking?view=mrtkunity-2022-05

**Comment by fwild** [comment]
Implemented, therefore closing.
