### ISSUE TITLE
Glyph, VFX, Image and Video augmentations are all movable in play mode

### ISSUE THREAD

**Issue by robhillman97** [WEKIT-ECS/MIRAGE-XR#879]
When in play mode the Glyph, VFX, Image and Video augmentations can all be moved as you would in edit mode.

**Comment by robhillman97** [comment]
This issue has been resolved on android (and IOS?) However, on HoloLens only the image is not movable in edit mode and Glyph, VFX, and Video augmentations are still movable,

**Comment by cawke** [comment]
did you update the data from the branch? I added new changes to this task yesterday

**Comment by robhillman97** [comment]
I cloned the refactoring branch this morning and built and tested from there. The latest commit was [885 Fixed](https://github.com/WEKIT-ECS/MIRAGE-XR/commit/92736a2604556da91b638c0a582fe06e97d4e644).

**Comment by robhillman97** [comment]
Just double checked and looks like it is fixed, not sure what happened earlier but must have been something I did. Closing the issue now
