### ISSUE TITLE
No calibration pop up

### ISSUE THREAD

**Issue by robhillman97** [WEKIT-ECS/MIRAGE-XR#880]
When loading an activity on HoloLens the user is not prompted to calibrate. (release branch)

**Comment by fwild** [comment]
I tested the RC 1.9 (MirageXR_1.8.93.0_Test, build from 18.5.2022) on HL2: the calibration pop up is there. The video is not displayed - but that's related to the pipeline build bug (which happens with several icons as well). Therefore closing the ticket.
