### ISSUE TITLE
Mobile Image augmentation not loading correctly.

### ISSUE THREAD

**Issue by robhillman97** [WEKIT-ECS/MIRAGE-XR#882]
An image augmentation created on a mobile device will show a red question mark when the activity is downloaded onto another device.

**Comment by fominykh** [comment]
Confirm that I could reproduce it too.

**Comment by cawke** [comment]
cannot be reproduced

**Comment by fominykh** [comment]
I could reproduce it 5 days ago. Tried again today and could not reproduce it. Might have been something in the learn.wekit-ecs.com server?
