### ISSUE TITLE
Image Augmentation Rotates with task station

### ISSUE THREAD

**Issue by robhillman97** [WEKIT-ECS/MIRAGE-XR#883]
The image augmentation will rotate and move around a task station similar to the panels connected to the diamond.

**Comment by fwild** [comment]
Do you mean that it is billboarded (= orientation follows user)? But the location stays the correct one? That's a feature!

**Comment by robhillman97** [comment]
No the billboard would not rotate in place but its position would rotate around the task station as you walked around it.  May have been fixed in the new build though.

**Comment by robhillman97** [comment]
Tested on the android build posted yesterday and still seems to be there. Here's a video of what I am seeing:

https://drive.google.com/file/d/1HqnMH_x8yGPjWtyc8ll_cy6wPEQS6Ot2/view?usp=sharing

**Comment by fwild** [comment]
indeed a bug
