### ISSUE TITLE
Create Robotic augmentation for eROBSON

### ISSUE THREAD

**Issue by jafarigit** [WEKIT-ECS/MIRAGE-XR#886]
A new type of augmentation for eROBSON project should be added to the augmentation list. For now it would be "Robotic" but it can be changed later. This augmentation contains a list of components which will be spawned on some markers, and they will interact with each other.

**Comment by fwild** [comment]
Could also be a "plugin"? not sure which one is better?

**Comment by jafarigit** [comment]
I think the current plugin augmentation limits us. It hasn't capability to implement all our functionality. eRobson needs a lot of objects and classes.

**Comment by fwild** [comment]
Sound reasonable!

**Comment by jafarigit** [comment]
eRobson augmentation is added.
