### ISSUE TITLE
Create a reference image library using markers of components

### ISSUE THREAD

**Issue by jafarigit** [WEKIT-ECS/MIRAGE-XR#887]
A new AR foundation reference image library which contains the markers of components (for every kit(e.g. Arduino) has many components).

**Comment by fwild** [comment]
Heads up: we will remove the image marker augmentation in the future, integrating its functionality into the task station itself. Don't think this will affect you, but though I mention!

**Comment by jafarigit** [comment]
Since we are going to use the new imageMarkerManager, I will close this ticket
