### ISSUE TITLE
Some augmentations and the task-station diamond move-rotate around a point in space

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#893]
Testing refactor version on iPad v1.9 testflight and refactoring APK from 04 May
How to reproduce:
1. Calibrated. Created an activity on iPad. Added 1 label and 3 Act glyphs. Saved the activity.
2. Close the app. Start the app again.
3. Open activity on the same device. See that:

- 2 Act glyphs are in the correct locations, but rotated 90 degrees. However, these act glyphs are fixed in the physical space.
- Label is fixed in space and only rotates towards me
- [REPORTED BUG] The third glyph and the task station are both moving and rotating when I move the device. it looks like these are moving around some point in space (possible where I started the app).

**Comment by fwild** [comment]
In the APK from yesterday (19.5.2022), images/task station diamond/glyphs are no longer pushed away by the user, nor does the image rotate in a circle (but properly billboards now). I therefore edit this ticket to focus on the remainder: the calibration is still not quite right: for me, when calibrating, the locations are somewhere else (seems a bit like 90 degree rotated to the left or right?). They are no longer rotating horizontally, but only angle rotate around the vertical axis?

**Comment by fwild** [comment]
This is a new behaviour, so I will report a new bug - I think the behaviour described here has been fixed. Mikhail?

**Comment by fwild** [comment]
Weirdly enough, I cannot reproduce this behaviour - something else must have gone wrong. I can create a new activity, calibrate, and then save/load/calibrate (with hard quitting the app or without), and they seem to show up in the right locations (maybe a tad too high? but that may have to do with Android spatial mapping). I close the ticket for now, so we can test and report new behaviour. One thing I want to test in particular is: does the calibration still work if you first create the activity + augmentations and then calibrate as the last step before saving (= augmentations have been placed and their location needs to be recalculated and upated as they are then relative to a new activity world origin).
