### ISSUE TITLE
Tutorial: some small wordings and small items

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#898]
* When you enter the + activity creation, the first step tells you about the "workstation" -> this should be "task station".
* Moreover, this dialogue was facing for me somewhere odd, as my action list was placed somewhat odd (it was 90 degrees turned, with the side facing me, so the tutorial dialogue was sidewards-facing me as well) - the tutorial text and arrow should be placed user facing (maybe with billboard?) and relative to the task station, not relative to the action list?
* next step: tapping the activity name is tricky while the action list is unlocked. Maybe there should be a dialogue step before that forces the user to lock it again?
* below the cloud icon, I can see a small text saying "progress" - is this from the tutorial? Does not make much sense?
* the edit mode tutorial ends abruptly for me (after I deleted the action step - or did I go wrong and should have deleted the augmentation instead?) - would be good to have a "you finished the tutorial" type message at the end?

**Comment by fwild** [comment]
This was on Hololens 2

**Comment by fwild** [comment]
I think there was a fix - the tutorial now (RC 1.9, 18.5.2022, HL2) ends now with the cloud save - is this the last step? Would be good to have a final dialogue message that says "congratulations you finished the tutorial" or something?

**Comment by BorisJov** [comment]
Yeah, it should be ending with the save step, that's good at least. I'll be doing the improvements today and will add the end message and the other things.
The dialogue position (rotation) is a bit tricky to get right. Sometimes it looks good when I test it, but it may not look the same on HL2.
The "progress" thing shouldn't be from the tutorial.
I'll also add a step to lock the activity window.
