### ISSUE TITLE
add CNR ITD logo

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#913]
CNR ITD has been contributing (with the Alien character model, animations, code), so should be acknowledged on the logo wall.

**Comment by MariellaF** [comment]
[cnrLogo.zip](https://github.com/WEKIT-ECS/MIRAGE-XR/files/8777624/cnrLogo.zip)
Hi Fridolin, here you can find our Logo. 
Let me know if it's ok.

**Comment by Callustian** [comment]
Working on 913_cnr_itd_logo
