### ISSUE TITLE
Add LRS url to settings screen

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#914]
For the ARETE pilot, we need the LRS to be configurable - please add to settings screen as a dropdown, so the API key is hidden from the user.

**Comment by BorisJov** [comment]
Needed details are set here:
https://github.com/WEKIT-ECS/MIRAGE-XR/blob/56ba34e6aaf1d35acdc8ccd4ead5e90f20869ca9/Assets/MirageXR/Common/Scripts/Services/MirageXRServiceBootstrapper.cs#L30

We need:
1. URL
2. Access token
3. xAPI version (almost always 1.0.3)

**Comment by BorisJov** [comment]
xAPI token seems to be stored here (best settable in Unity Inspector):
https://github.com/WEKIT-ECS/MIRAGE-XR/blob/56ba34e6aaf1d35acdc8ccd4ead5e90f20869ca9/Assets/MirageXR%20xAPI%20Client.asset#L15

**Comment by fwild** [comment]
That's not easy then to enter, so we either add a drop down with preconfigured LRS (I would almost prefer that option), or we have to sign something between WEKIT and ARETE.
