### ISSUE TITLE
Android build pipeline fails with pkgmanager error

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#929]
See log file:
"[Package Manager] Done resolving packages in 69.90s seconds
An error occurred while resolving packages:
  One or more packages could not be added to the local file system:
    com.microsoft.mixedreality.toolkit.examples: Cannot connect to 'pkgs.dev.azure.com' (error code: ECONNRESET). Verify your environment firewall policies allow connection to this host name. If your system is behind a proxy, verify your proxy environment variables (HTTP_PROXY and HTTPS_PROXY) are properly set."

**Comment by fwild** [comment]
Running out of disk space on our Linux runner:
You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 23 MB. This might explain the previous error from package manager, too (the MRTk examples cannot connect to azure)
(https://mirage-community.slack.com/archives/C035QT80XGT/p1654252319524299).

There is no option to clear the caches
How do I reset the Linux runner? 
It seems to keep cache 7 days per default, and I think we simply pushed too much…?

We could add a manual action for clearing the cache? As described here? 

[Clear cache in GitHub Actions](https://stackoverflow.com/questions/63521430/clear-cache-in-github-actions)

I am surprised, though
Any other thoughts?

Hm. Retention of build artifacts: 90 days seems a lot…?

Cache size is only 559mb, so should be ok

And I would think the games-ci image generally should also be ok (though there are some proposals floating around for deleting some shared libs…)

We would have to change on develop for the pipeline scripts to run
Right?

**Comment by Callustian** [comment]
Could I suggest the use of `tree --du -h -d`? It is possible you have to install the command.
