### ISSUE TITLE
Calibration: Upload calibration marker to app store images

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#932]
Put the marker also with the images in the store, so users can get the marker from there, too.

**Comment by fwild** [comment]
@fominykh @cawke do you think this is still needed? We have the "get calibration image" in the app now (even if it does not work yet), and in my view that's a better way than this?

**Comment by fominykh** [comment]
Not strictly necessary. Also given that we want to potentially allow to use custom images, we can drop this issue.
By the way, "Get calibration image" does nothing for me in the app.

**Comment by fwild** [comment]
No longer needed, sharing feature is better
