### ISSUE TITLE
The pictures should be standardized for the new UI.

### ISSUE THREAD

**Issue by Alvareon** [WEKIT-ECS/MIRAGE-XR#951]
Reimport the pictures for UI2.0
1. Import all icons to 512x512 px;
2. Import the buttons, borders and frames to 9-slice (see the example: Assets/MirageXR/Design/UI_Elements/PNG/Base/border_10.png).
3. Rename the pictures in an understandable names. For example: "Frame 336450" to "login_frame", etc (both in the Figma and Unity)

https://docs.unity3d.com/Manual/9SliceSprites.html

**Comment by cawke** [comment]
![image](https://user-images.githubusercontent.com/20320355/174085816-cb9ff52d-4df7-4c45-9085-855a6563566c.png)
