### ISSUE TITLE
Add new fonts to the project

### ISSUE THREAD

**Issue by Alvareon** [WEKIT-ECS/MIRAGE-XR#953]
SF Pro Text, SF Pro Display

see: https://www.figma.com/file/AqAGvX0KRDNRlVz3KFzoMH/New-Concept?node-id=373%3A11005

Convert with TMP Font Asset Creator:
https://docs.unity3d.com/Packages/com.unity.textmeshpro@4.0/manual/FontAssetsCreator.html
(use for all font types: bold, italics, ... see current font)

Add special characters (Greek, Cyrillic, ...), see current font in the project.

Likely requires setting the new font in the relevant dialogues by hand.

**Comment by cawke** [comment]
![image](https://user-images.githubusercontent.com/20320355/174086236-61cae851-e42a-47e1-9a8a-0868135ea738.png)

**Comment by fwild** [comment]
So, this is now done, right? @Alvareon

**Comment by Alvareon** [comment]
added SF Pro Text and SF Pro Display
