### ISSUE TITLE
Implement SSO/Register functionality to the server

### ISSUE THREAD

**Issue by Alvareon** [WEKIT-ECS/MIRAGE-XR#954]
Currently, users go to this web form to register: https://learn.wekit-ecs.com/login/signup.php
After a new user submits this form, they receive a validation email, and they have to click on the link embedded in the email to activate their account. Only after they clicked this activation link, the account is live, and the user can log in on the app.

This ticket is about embedding the registration form and submit procedure within the app. Email activation will always be required, but maybe we are willing to accept alternatives (like SMS activation)? Maybe there is also a smart way to make the app know when a user account has been activated, so the app can automatically log in, once the activation link has been clicked?

Linked to: https://github.com/WEKIT-ECS/MIRAGE-XR/issues/972

**Comment by fwild** [comment]
SSO projects do not provide an API for that, so let's not implement this for now, but simply link to the web signup page.
