### ISSUE TITLE
Update New Activity screen according Figma

### ISSUE THREAD

**Issue by Alvareon** [WEKIT-ECS/MIRAGE-XR#958]
The little preview window in the activity list.

**Comment by Alvareon** [comment]
![555](https://user-images.githubusercontent.com/34060044/193036758-045ed906-3494-4de3-b572-36a59f4f9602.png)

**Comment by Alvareon** [comment]
TODO:
- remove navigation buttons
- use tap instead of navigation buttons
- move edit button (?)

**Comment by fominykh** [comment]
The vertical spaces between the elements on this screen are too large compared to the design. 
![image](https://user-images.githubusercontent.com/10297277/194327073-fca96675-9c32-4052-adef-4a816b01afac.png)
![image](https://user-images.githubusercontent.com/10297277/194327307-48c22c58-727c-4722-9626-04c6e2baf474.png)

**Comment by Alvareon** [comment]
https://github.com/WEKIT-ECS/MIRAGE-XR/pull/1074
