### ISSUE TITLE
Add editors for different content type

### ISSUE THREAD

**Issue by Alvareon** [WEKIT-ECS/MIRAGE-XR#970]

**Comment by fwild** [comment]
Heads-up: currently, when you re-edit a 3D model, it brings up the action augmentation edit panel.

**Comment by Alvareon** [comment]
[the part 1](https://github.com/WEKIT-ECS/MIRAGE-XR/pull/1048)

**Comment by fwild** [comment]
Split into separate tickets, some implemented, some open. closing.
