### ISSUE TITLE
Add preview activity

### ISSUE THREAD

**Issue by Alvareon** [WEKIT-ECS/MIRAGE-XR#971]
![Screenshot 2022-06-16 at 15 20 04](https://user-images.githubusercontent.com/183296/174091086-472da013-d4f2-4ce0-8762-7f7b0dd96989.png)

![Screenshot 2022-06-16 at 15 20 42](https://user-images.githubusercontent.com/183296/174091239-360d467e-5be1-40e1-af35-d867f9ee1068.png)

**Comment by fwild** [comment]
Should do the following: switch to playmode

**Comment by fwild** [comment]
(same as the edit toggle on top)

**Comment by fwild** [comment]
and subsequently in playmode offer a big fat "return to editing" button

**Comment by fwild** [comment]
Let's do the simple version for version 2: clicking the button switches to playmode.
