### ISSUE TITLE
Create the Port class

### ISSUE THREAD

**Issue by jafarigit** [WEKIT-ECS/MIRAGE-XR#981]
Create the port class which will detect the connected port and be connected to that port. The port class will detect the type of the connected bit as well.

**Comment by fwild** [comment]
Is this mqtt? or which protocol? Because we do have mqtt support already integrated (and I would think that any similar IoT protocol could simply piggy back on thse...

**Comment by jafarigit** [comment]
By port  I meant the port of the bit components like minus or plus port

**Comment by jafarigit** [comment]
This task is done
